/* Listings for "What should we do today?" — Toronto.

   Every entry carries `source` and `checked`: the page the schedule came from
   and the date it was last confirmed. Anything that could not be confirmed
   against a primary source was left out rather than guessed. Re-check before
   the season turns — see README. */

const CHECKED = '2026-09-08';

const CATEGORIES = {
  museum:       { label: 'Museum',            art: 'art-museum'        },
  art:          { label: 'Art & exhibitions', art: 'art-gallery'       },
  market:       { label: 'Farmers’ market',   art: 'art-market'        },
  flea:         { label: 'Flea market',       art: 'art-flea'          },
  books:        { label: 'Books',             art: 'art-books'         },
  architecture: { label: 'Architecture',      art: 'art-architecture'  },
  festival:     { label: 'Festivals',         art: 'art-festival'      },
  dropin:       { label: 'Drop-ins',          art: 'art-tools'         },
  social:       { label: 'Meetups',           art: 'art-mic'           },
  comedy:       { label: 'Comedy',            art: 'art-neon'          },
};

/* Price buckets for the filter. These are derived from each listing's `entry`
   text rather than stored beside it, so there is one source of truth: the
   line the card actually shows. Scraped listings get bucketed for free — the
   poller already writes `entry` as "Free" or "$N" from JSON-LD offers.
   Order here is the order the filter lists them in. */
const PRICES = {
  free:    { label: 'Free'             },
  under20: { label: 'Under $20'        },
  over20:  { label: '$20 and up'       },
  unknown: { label: 'Price not listed' },
};

/* schedule kinds
   range  { kind:'range',  start, end }
   day    { kind:'day',    date, time?, hour? }
   weekly { kind:'weekly', weekday, from, to, time?, hour? }
            weekday is 0=Sunday, or an array of them
   nth    { kind:'nth',    weekday, nth, from, to, time?, hour? }
            nth is 1..5, or -1 for the last of the month                */

const EVENTS = [
  /* ------------------------------------------------------------ markets */
  {
    id: 'wychwood-barns',
    title: 'The Stop’s Farmers’ Market',
    category: 'market',
    entry: 'Free',
    art: 'art-market',
    venue: 'Artscape Wychwood Barns',
    address: '601 Christie St, Toronto, ON M6G 4C7',
    url: 'https://www.thestop.org/farmersmarket/',
    source: 'https://www.thestop.org/farmersmarket/',
    checked: CHECKED,
    description: 'One of the few markets in the city that runs all year — outdoors along the walkways May to October, inside the main Barn November to April.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-01-01', to: '2026-12-31', time: '8am–1pm', hour: 8 },
  },
  {
    id: 'brick-works',
    title: 'Evergreen Brick Works Farmers Market',
    category: 'market',
    entry: 'Free',
    art: 'art-ravine',
    venue: 'Evergreen Brick Works',
    address: '550 Bayview Ave, Toronto, ON M4W 3X8',
    url: 'https://www.evergreen.ca/evergreen-brick-work/activities/saturday-farmers-market/',
    source: 'https://www.evergreen.ca/evergreen-brick-work/activities/saturday-farmers-market/',
    checked: CHECKED,
    description: 'Ontario growers in a former brick factory, snow or shine. Outdoors May to October, indoors from 9am November to April. Walk the ravine trails after.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-01-01', to: '2026-12-31', time: '8am–1pm', hour: 8 },
  },
  {
    id: 'st-lawrence',
    title: 'St. Lawrence Farmers’ Market',
    category: 'market',
    entry: 'Free',
    art: 'art-bread',
    venue: 'St. Lawrence Market North',
    address: '92 Front St E, Toronto, ON M5E 1C4',
    url: 'https://www.stlawrencemarket.com/pages/hours_parking/',
    source: 'https://www.stlawrencemarket.com/pages/hours_parking/',
    checked: CHECKED,
    description: 'Farmers have taken the north building on Saturdays since 1803, now in the new hall that opened in 2026. Doors from five in the morning.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-01-01', to: '2026-12-31', time: '5am–3pm', hour: 5 },
  },
  {
    id: 'dufferin-grove',
    title: 'Dufferin Grove Organic Farmers’ Market',
    category: 'market',
    entry: 'Free',
    art: 'art-jar',
    venue: 'Dufferin Grove Park Clubhouse',
    address: '875 Dufferin St, Toronto, ON M6H 3L3',
    url: 'https://dufferinpark.ca/market/',
    source: 'https://www.familyfuncanada.com/toronto/outdoor-farmers-markets-toronto/',
    checked: CHECKED,
    description: 'All-organic and year-round, at the clubhouse. Small enough to talk to everyone selling.',
    schedule: { kind: 'weekly', weekday: 4, from: '2026-01-01', to: '2026-12-31', time: '3–7pm', hour: 15 },
  },
  {
    id: 'sorauren',
    title: 'Sorauren Farmers’ Market',
    category: 'market',
    entry: 'Free',
    art: 'art-corn',
    venue: 'Sorauren Avenue Park',
    address: '50 Wabash Ave, Toronto, ON M6R 1H8',
    url: 'https://soraurenmarket.com/',
    source: 'https://www.familyfuncanada.com/toronto/outdoor-farmers-markets-toronto/',
    checked: CHECKED,
    description: 'A Monday-evening market in Roncesvalles — dinner from a stall, eaten on the grass while the dog park fills up. Runs to October 26.',
    schedule: { kind: 'weekly', weekday: 1, from: '2026-05-04', to: '2026-10-26', time: '3–7pm', hour: 15 },
  },
  {
    id: 'withrow',
    title: 'Withrow Park Farmers’ Market',
    category: 'market',
    entry: 'Free',
    art: 'art-tent',
    venue: 'Withrow Park',
    address: '725 Logan Ave, Toronto, ON M4K 3C7',
    url: 'https://withrowmarket.ca/',
    source: 'https://www.blogto.com/eat_drink/2026/07/9-farmers-markets-toronto-summer/',
    checked: CHECKED,
    description: 'The east end’s Saturday morning ritual, in the shade at the north end of the park. Last market of the season is October 17.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-06-06', to: '2026-10-17', time: '9am–1pm', hour: 9 },
  },
  {
    id: 'trinity-bellwoods-market',
    title: 'Trinity Bellwoods Farmers Market',
    category: 'market',
    entry: 'Free',
    art: 'art-market',
    venue: 'Trinity Bellwoods Park, at Dundas and Shaw',
    address: '1053 Dundas St W, Toronto, ON M6J 1W9',
    url: 'https://www.tbfm.ca/',
    source: 'https://www.tbfm.ca/',
    checked: CHECKED,
    description: 'Tuesday afternoons at the Dundas end of the park. Seasonal, and the excuse you needed to stay until dark. Runs to October 27.',
    schedule: { kind: 'weekly', weekday: 2, from: '2026-05-05', to: '2026-10-27', time: '3–7pm', hour: 15 },
  },

  /* ------------------------------------------------------------ museums */
  {
    id: 'ago-first-wednesday',
    title: 'AGO First Wednesday Night Free',
    category: 'museum',
    entry: 'Free, but book the timed ticket ahead',
    art: 'art-museum',
    venue: 'Art Gallery of Ontario',
    address: '317 Dundas St W, Toronto, ON M5T 1G4',
    url: 'https://ago.ca/visit/free-wednesday-nights',
    source: 'https://ago.ca/visit/free-wednesday-nights',
    checked: CHECKED,
    description: 'Free admission on the first Wednesday night of the month — not every Wednesday. Tickets are released online at 10am the Monday before, two per person, and they go.',
    schedule: { kind: 'nth', weekday: 3, nth: 1, from: '2026-01-01', to: '2026-12-31', time: '6–9pm', hour: 18 },
  },
  {
    id: 'gardiner-wednesday',
    title: 'Gardiner Museum Free Wednesdays',
    category: 'museum',
    entry: 'Free',
    art: 'art-vase',
    venue: 'Gardiner Museum',
    address: '111 Queens Park, Toronto, ON M5S 2C7',
    url: 'https://www.gardinermuseum.on.ca/visit/hours-admission/',
    source: 'https://www.gardinermuseum.on.ca/visit/hours-admission/',
    checked: CHECKED,
    description: 'Free every Wednesday afternoon and evening, no booking needed. Three floors of ceramics across from the ROM, done in an hour. Always free for students, under-18s and Indigenous Peoples.',
    schedule: { kind: 'weekly', weekday: 3, from: '2026-01-01', to: '2026-12-31', time: '4–9pm', hour: 16 },
  },
  {
    id: 'aga-khan-wednesday',
    title: 'BMO Free Wednesdays at the Aga Khan',
    category: 'museum',
    entry: 'Free; tickets in person only',
    art: 'art-arch',
    venue: 'Aga Khan Museum',
    address: '77 Wynford Dr, North York, ON M3C 1K1',
    url: 'https://agakhanmuseum.org/whats-on/bmo-free-wednesdays/',
    source: 'https://agakhanmuseum.org/whats-on/bmo-free-wednesdays/',
    checked: CHECKED,
    description: 'Free galleries during extended Wednesday hours. Tickets are in person only, at the guest services desk. Worth the trip up for the building and the reflecting pools alone.',
    schedule: { kind: 'weekly', weekday: 3, from: '2026-01-01', to: '2026-12-31', time: '4–8pm', hour: 16 },
  },
  {
    id: 'bata-pwyc',
    title: 'Bata Shoe Museum pay-what-you-can',
    category: 'museum',
    entry: 'Pay what you can',
    art: 'art-shoe',
    venue: 'Bata Shoe Museum',
    address: '327 Bloor St W, Toronto, ON M5S 1W7',
    url: 'https://batashoemuseum.ca/visit-us/',
    source: 'https://batashoemuseum.ca/visit-us/',
    checked: CHECKED,
    description: 'Thursday evenings are pay-what-you-can. Four and a half thousand years of footwear, which is better than it sounds.',
    schedule: { kind: 'weekly', weekday: 4, from: '2026-01-01', to: '2026-12-31', time: '5–8pm', hour: 17 },
  },
  {
    id: 'bata-free-sunday',
    title: 'Bata Shoe Museum free Sundays',
    category: 'museum',
    entry: 'Free',
    art: 'art-lamp',
    venue: 'Bata Shoe Museum',
    address: '327 Bloor St W, Toronto, ON M5S 1W7',
    url: 'https://batashoemuseum.ca/visit-us/',
    source: 'https://batashoemuseum.ca/visit-us/',
    checked: CHECKED,
    description: 'Free for everyone, every Sunday, for the museum’s shorter afternoon hours.',
    schedule: { kind: 'weekly', weekday: 0, from: '2026-01-01', to: '2026-12-31', time: '12–5pm', hour: 12 },
  },

  /* -------------------------------------------------- art & exhibitions */
  {
    id: 'auf-der-maur',
    title: 'Melissa Auf der Maur: My ’90s Rock Photographs',
    category: 'art',
    entry: '$30 general admission; free for Ontarians 14 to 24',
    art: 'art-camera',
    venue: 'Art Gallery of Ontario',
    address: '317 Dundas St W, Toronto, ON M5T 1G4',
    url: 'https://ago.ca/exhibitions/melissa-auf-der-maur-my-90s-rock-photographs',
    source: 'https://ago.ca/press-release/raw-and-contemplative-melissa-auf-der-maur-my-90s-rock-photographs-opens-september-2',
    checked: CHECKED,
    description: 'A backstage pass to the last analogue decade, shot by the Hole and Smashing Pumpkins bassist. Opens to the public today; runs into next summer.',
    schedule: { kind: 'range', start: '2026-09-08', end: '2027-06-30' },
  },
  {
    id: 'sunday-best',
    title: 'Sunday Best: The Power & The Glory of Black Style',
    category: 'art',
    entry: '$30 general admission; free for Ontarians 14 to 24',
    art: 'art-gallery',
    venue: 'Art Gallery of Ontario',
    address: '317 Dundas St W, Toronto, ON M5T 1G4',
    url: 'https://ago.ca/exhibitions/sunday-best-power-glory-black-style',
    source: 'https://ago.ca/press-release/exploring-ritual-and-rebellion-woven-black-style-sunday-best-debuts-ago-fall',
    checked: CHECKED,
    description: 'Ritual and rebellion in Black style and self-fashioning. Members from October 7, passholders October 9, everyone else from October 13.',
    schedule: { kind: 'range', start: '2026-10-13', end: '2027-02-28' },
  },
  {
    id: 'onsite-returning',
    title: 'Returning to Ourselves',
    category: 'art',
    closes: '5pm',
    entry: 'Free',
    art: 'art-sculpture',
    venue: 'Onsite Gallery, OCAD University',
    address: '199 Richmond St W, Toronto, ON M5V 0H4',
    url: 'https://www.ocadu.ca/galleries/onsite-gallery',
    source: 'https://akimbo.ca/listings/fall-2026-exhibitions-programs-at-onsite-gallery/',
    checked: CHECKED,
    description: 'Forty years of Rebecca Baird and Kenny Alvin Baird, shown alongside work by Inuk artist Michael Massie. Free, and usually empty on a weekday afternoon.',
    schedule: { kind: 'range', start: '2026-09-02', end: '2027-01-30' },
  },
  {
    id: 'image-centre',
    title: 'The Image Centre fall exhibitions',
    category: 'art',
    closes: '5pm',
    entry: 'Free',
    art: 'art-neon',
    venue: 'The Image Centre, Toronto Metropolitan University',
    address: '33 Gould St, Toronto, ON M5B 1W1',
    url: 'https://theimagecentre.ca/gallery/',
    source: 'https://theimagecentre.ca/visit/',
    checked: CHECKED,
    description: 'The Main and University galleries reopen after installation, with a fall opening reception on September 9, 6–8pm. Free, two minutes from Dundas station.',
    schedule: { kind: 'range', start: '2026-09-09', end: '2026-12-05' },
  },
  {
    id: 'rom-survival',
    title: 'A Story of Survival at the ROM',
    category: 'art',
    closes: '5:30pm',
    entry: 'Included with admission, plus a surcharge; varies by date',
    art: 'art-fossil',
    venue: 'Royal Ontario Museum',
    address: '100 Queens Park, Toronto, ON M5S 2C6',
    url: 'https://www.rom.on.ca/whats-on/exhibitions',
    source: 'https://www.rom.on.ca/whats-on/exhibitions',
    checked: CHECKED,
    description: 'Closes October 18. The Dawn of Life galleries downstairs are included, and are the better hour anyway.',
    schedule: { kind: 'range', start: '2026-09-08', end: '2026-10-18' },
  },
  {
    id: 'abya-yala',
    title: 'The Allegorical Archipelago of Abya Yala opens',
    category: 'art',
    closes: '5:30pm',
    entry: 'Included with general admission, which varies by date',
    art: 'art-arch',
    venue: 'Royal Ontario Museum',
    address: '100 Queens Park, Toronto, ON M5S 2C6',
    url: 'https://www.rom.on.ca/whats-on/exhibitions',
    source: 'https://www.rom.on.ca/whats-on/exhibitions',
    checked: CHECKED,
    description: 'Opening day of the ROM’s new fall exhibition. Closing date had not been posted when this was checked.',
    schedule: { kind: 'day', date: '2026-09-26' },
  },
  {
    id: 'moca-fall-opens',
    title: 'MOCA fall season opens',
    category: 'art',
    closes: '5pm',
    entry: '$14; free for 18 and under',
    art: 'art-records',
    venue: 'Museum of Contemporary Art Toronto',
    address: '158 Sterling Rd, Toronto, ON M6R 2B7',
    url: 'https://moca.ca/exhibitions/',
    source: 'https://moca.ca/press-releases/moca-announces-fall-2026-exhibition-details/',
    checked: CHECKED,
    description: 'Bharti Kher and Delcy Morelos, with Beverly Glenn-Copeland’s Light of the Heavens, across two floors of a converted aluminium factory. Free for anyone eighteen and under.',
    schedule: { kind: 'day', date: '2026-10-04' },
  },
  {
    id: 'nuit-blanche',
    title: 'Nuit Blanche Toronto',
    category: 'art',
    entry: 'Free',
    art: 'art-star',
    venue: 'Across the city',
    address: 'Nathan Phillips Square, 100 Queen St W, Toronto, ON M5H 2N2',
    url: 'https://nbto.com/',
    source: 'https://www.destinationontario.com/en-ca/articles/guide-toronto-nuit-blanche',
    checked: CHECKED,
    description: 'Free contemporary art from 7pm to 7am. Pick one neighbourhood and walk it properly instead of chasing the map.',
    schedule: { kind: 'day', date: '2026-10-03', time: '7pm–7am', hour: 19 },
  },
  {
    id: 'art-toronto',
    title: 'Art Toronto',
    category: 'art',
    entry: '$35 to October 1, then $40, plus HST and a $2 fee',
    art: 'art-filmreel',
    venue: 'Metro Toronto Convention Centre',
    address: '255 Front St W, Toronto, ON M5V 2W6',
    url: 'https://arttoronto.ca/home/',
    source: 'https://arttoronto.ca/home/',
    checked: CHECKED,
    description: 'The country’s art fair. A day pass runs past twenty dollars, but it is the entire scene in one room.',
    schedule: { kind: 'range', start: '2026-10-29', end: '2026-11-01' },
  },

  /* --------------------------------------------------------------- flea */
  {
    id: 'toronto-flea',
    title: 'Toronto Flea',
    category: 'flea',
    entry: 'Free',
    art: 'art-flea',
    venue: 'Ashbridge Estate',
    address: '1444 Queen St E, Toronto, ON M4L 1E1',
    url: 'https://artsmarket.ca/toronto-flea/',
    source: 'https://festmore.com/events/leslieville-flea-market-toronto-2026',
    checked: CHECKED,
    description: 'Formerly the Leslieville Flea. Furniture, records and mid-century everything on the lawn of a two-hundred-year-old farmhouse. Last Sunday of the season is October 4.',
    schedule: { kind: 'weekly', weekday: 0, from: '2026-05-03', to: '2026-10-04', time: '11am–5pm', hour: 11 },
  },
  {
    id: 'kensington-pedestrian-sundays',
    title: 'Pedestrian Sundays in Kensington',
    category: 'flea',
    entry: 'Free',
    art: 'art-lantern',
    venue: 'Kensington Market',
    address: 'Augusta Ave & Baldwin St, Toronto, ON M5T 2L7',
    url: 'https://www.pskensington.ca/',
    source: 'https://www.todocanada.ca/city/toronto/event/pedestrian-sundays-kensington-market/',
    checked: CHECKED,
    description: 'Cars out, everyone else in: drum circles, stoop sales, and the market at its loudest. Augusta stays closed to 10pm. Last Sunday of the month, May to October.',
    schedule: { kind: 'nth', weekday: 0, nth: -1, from: '2026-05-01', to: '2026-10-31', time: '12–7pm', hour: 12 },
  },
  {
    id: 'toronto-vintage-show',
    title: 'Toronto Vintage Show',
    category: 'flea',
    closes: '5pm',
    entry: '$17 at the door, single day, credit or debit only',
    art: 'art-shoe',
    venue: 'Queen Elizabeth Building, Exhibition Place',
    address: '190 Princes’ Blvd, Toronto, ON M6K 3C3',
    url: 'https://www.torontovintageshow.ca/',
    source: 'https://www.torontovintageshow.ca/',
    checked: CHECKED,
    description: 'Dealers of vintage clothing, textiles and antiques under one roof. Saturday 9am–6pm, Sunday 10am–5pm.',
    schedule: { kind: 'range', start: '2026-09-26', end: '2026-09-27' },
  },
  {
    id: 'one-of-a-kind',
    title: 'One of a Kind Christmas Show',
    category: 'flea',
    entry: '$23 adult early bird to Nov 27, when it opens',
    art: 'art-tree',
    venue: 'Enercare Centre, Exhibition Place',
    address: '100 Princes’ Blvd, Toronto, ON M6K 3C3',
    url: 'https://oneofakindshow.com/home/2026-christmas-show/',
    source: 'https://oneofakindshow.com/home/2026-christmas-show/',
    checked: CHECKED,
    description: 'Hundreds of Canadian makers in one hall for ten days. Every present you owe anyone, solved in an afternoon.',
    schedule: { kind: 'range', start: '2026-11-27', end: '2026-12-06' },
  },

  /* -------------------------------------------------------------- books */
  {
    id: 'word-on-the-street',
    title: 'The Word On The Street',
    category: 'books',
    entry: 'Free',
    art: 'art-books',
    venue: 'David Pecaut Square',
    address: '55 John St, Toronto, ON M5V 3G4',
    url: 'https://toronto.thewordonthestreet.ca/',
    source: 'https://toronto.thewordonthestreet.ca/event-directory/annual-festival/2026-festival/',
    checked: CHECKED,
    description: 'Canada’s largest literary festival, free, over two days — small presses, magazine tables, and authors reading in tents. Its 37th year.',
    schedule: { kind: 'range', start: '2026-09-26', end: '2026-09-27' },
  },
  {
    id: 'tifa',
    title: 'Toronto International Festival of Authors',
    category: 'books',
    entry: '$29 weekday, $39 weekend day pass, plus HST',
    art: 'art-mic',
    venue: 'Victoria University, University of Toronto',
    address: '91 Charles St W, Toronto, ON M5S 1K7',
    url: 'https://festivalofauthors.ca/festival/',
    source: 'https://festivalofauthors.ca/2026/03/05/2026-festival-dates/',
    checked: CHECKED,
    description: 'Readings and on-stage interviews over five days. Moved off the Harbourfront campus to Victoria University — check the venue on your ticket.',
    schedule: { kind: 'range', start: '2026-10-28', end: '2026-11-01' },
  },

  /* ------------------------------------------------------- architecture */
  {
    id: 'tsa-downtown-yonge',
    title: 'Free architectural walking tours',
    category: 'architecture',
    entry: 'Free; the thematic tours are $15',
    art: 'art-architecture',
    venue: 'Toronto Society of Architects, Downtown Yonge',
    address: 'Yonge St & Dundas St, Toronto, ON M5B 1R8',
    url: 'https://torontosocietyofarchitects.ca/tours/',
    source: 'https://nowtoronto.com/event/free-architectural-walking-tours/',
    checked: CHECKED,
    description: 'Architect-led walks through Downtown Yonge, free, through to October 24. The society’s nine thematic tours elsewhere in the city are $15 and run 90 to 120 minutes.',
    schedule: { kind: 'range', start: '2026-07-12', end: '2026-10-24' },
  },
  {
    id: 'spadina-museum',
    title: 'Spadina Museum house tour',
    category: 'architecture',
    entry: 'Free',
    art: 'art-house',
    venue: 'Spadina Museum',
    address: '285 Spadina Rd, Toronto, ON M5R 2V5',
    url: 'https://www.toronto.ca/explore-enjoy/history-art-culture/museums/spadina-museum/',
    source: 'https://www.toronto.ca/explore-enjoy/history-art-culture/museums/spadina-museum/',
    checked: CHECKED,
    description: 'The house can only be seen on the tour, and the tour is free. Hourly from 11:15am, last one at 4. The grounds are yours either way.',
    schedule: { kind: 'weekly', weekday: [6, 0], from: '2026-01-01', to: '2026-12-31', time: 'hourly, 11:15am–4pm', hour: 11 },
  },
  {
    id: 'fort-york',
    title: 'Musket demonstrations at Fort York',
    category: 'architecture',
    entry: 'Free',
    art: 'art-cannon',
    venue: 'Fort York National Historic Site',
    address: '250 Fort York Blvd, Toronto, ON M5V 3K9',
    url: 'https://www.toronto.ca/explore-enjoy/history-art-culture/museums/fort-york-national-historic-site/',
    source: 'https://www.toronto.ca/explore-enjoy/history-art-culture/museums/fort-york-national-historic-site/',
    checked: CHECKED,
    description: 'Three firings a day in the shadow of the Gardiner, among the city’s oldest buildings. Weather permitting. The site itself is open Wednesday to Sunday.',
    schedule: { kind: 'weekly', weekday: [6, 0], from: '2026-01-01', to: '2026-12-31', time: '11:30am, 1:30 & 3:30pm', hour: 11 },
  },
  {
    id: 'bentway-summer-trail',
    title: 'Last day of the Bentway skate trail',
    category: 'architecture',
    entry: 'Free',
    art: 'art-skates',
    venue: 'The Bentway',
    address: '250 Fort York Blvd, Toronto, ON M5V 3K9',
    url: 'https://thebentway.ca/',
    source: 'https://curiocity.com/bentway-skating-trail-toronto-open-late-summer/',
    checked: CHECKED,
    description: 'The 220-metre figure-eight threaded between the columns of the Gardiner closes for the summer today. Go, or wait for the ice near Christmas.',
    schedule: { kind: 'day', date: '2026-09-27' },
  },

  /* ---------------------------------------------------------- festivals */
  {
    id: 'tiff',
    title: 'Toronto International Film Festival',
    category: 'festival',
    entry: '$30 and up for a regular screening, HST and fees included',
    art: 'art-tent',
    venue: 'TIFF Lightbox and King Street West',
    address: '350 King St W, Toronto, ON M5V 3X5',
    url: 'https://tiff.net/',
    source: 'https://www.tiff.net/about-the-festival',
    checked: CHECKED,
    description: 'The 51st festival: 293 films, King Street closed, and a full film market for the first time. Rush tickets are the only sane way in.',
    schedule: { kind: 'range', start: '2026-09-10', end: '2026-09-20' },
  },
  {
    id: 'cabbagetown-festival',
    title: 'Cabbagetown Festival',
    category: 'festival',
    entry: 'Free',
    art: 'art-corn',
    venue: 'Parliament Street',
    address: 'Parliament St & Carlton St, Toronto, ON M5A 2Z1',
    url: 'https://www.cabbagetownto.com/',
    source: 'https://curiocity.com/toronto-cabbagetown-festival/',
    checked: CHECKED,
    description: 'Toronto’s longest-running street festival, through the Victorian half of the east end. Saturday 11am–8pm, Sunday 11am–7pm.',
    schedule: { kind: 'range', start: '2026-09-12', end: '2026-09-13' },
  },
  {
    id: 'ukrainian-festival',
    title: 'Toronto Ukrainian Festival',
    category: 'festival',
    entry: 'Free',
    art: 'art-festival',
    venue: 'Bloor West Village',
    address: 'Bloor St W & Jane St, Toronto, ON M6S 1M9',
    url: 'https://ukrainianfestival.com/',
    source: 'https://ukrainianfestival.com/',
    checked: CHECKED,
    description: 'The largest Ukrainian street festival in North America, along Bloor West. Go for the varenyky, stay for the dancing.',
    schedule: { kind: 'range', start: '2026-09-18', end: '2026-09-20' },
  },
  {
    id: 'santa-claus-parade',
    title: 'The Original Santa Claus Parade',
    category: 'festival',
    entry: 'Free',
    art: 'art-lantern',
    venue: 'Bloor Street to St. Lawrence Market',
    address: 'Bloor St W & Christie St, Toronto, ON M6G 1M1',
    url: 'https://www.thesantaclausparade.com/the-parade',
    source: 'https://www.thesantaclausparade.com/the-parade',
    checked: CHECKED,
    unconfirmed: 'The 2026 date was not posted when this was checked — November 22 is the traditional third Sunday.',
    description: 'Running since 1905 and free from any curb on the route. Stand north of Bloor if you want to see anything.',
    schedule: { kind: 'day', date: '2026-11-22' },
  },
  {
    id: 'cavalcade-of-lights',
    title: 'Cavalcade of Lights opening night',
    category: 'festival',
    entry: 'Free',
    art: 'art-star',
    venue: 'Nathan Phillips Square',
    address: '100 Queen St W, Toronto, ON M5H 2N2',
    url: 'https://www.toronto.ca/explore-enjoy/festivals-events/cavalcade-of-lights/',
    source: 'https://www.toronto.ca/news/cavalcade-of-lights-returns-tomorrow-to-brighten-nathan-phillips-square/',
    checked: CHECKED,
    description: 'Live music from 6pm, the official tree lit at 6:30, and the rink opens. Free. The lights stay on nightly until 11pm through to January 7.',
    schedule: { kind: 'day', date: '2026-11-29', time: 'from 6pm', hour: 18 },
  },
  {
    id: 'distillery-winter-village',
    title: 'Distillery Winter Village',
    category: 'festival',
    entry: 'Free on weekdays, ticketed at weekends',
    art: 'art-jar',
    venue: 'Distillery Historic District',
    address: '55 Mill St, Toronto, ON M5A 3C4',
    url: 'https://thedistillerywintervillage.com/',
    source: 'https://thedistillerywintervillage.com/',
    checked: CHECKED,
    description: 'Cobblestones, a very large tree lit on opening night at 6pm, and mulled wine at a markup. Runs to January 3 — go on a weekday.',
    schedule: { kind: 'range', start: '2026-11-12', end: '2027-01-03' },
  },

  /* ----------------------------------------------------------- drop-ins */
  {
    id: 'gardiner-clay',
    title: 'Drop-in clay class at the Gardiner',
    category: 'dropin',
    closes: '5pm',
    art: 'art-sculpture',
    entry: '$22, plus $5 and up to fire a piece',
    venue: 'Gardiner Museum',
    address: '111 Queens Park, Toronto, ON M5S 2C7',
    url: 'https://www.gardinermuseum.on.ca/classes/',
    source: 'https://www.bloor-yorkville.com/events/drop-in-clay-classes-at-the-gardiner-museum/',
    checked: CHECKED,
    description: 'An hour at the wheel with no course to sign up for. Registration opens online at 10am the morning of each class and it goes quickly. Firing is extra and paid at the front desk.',
    schedule: { kind: 'weekly', weekday: [3, 6], from: '2026-01-01', to: '2026-12-31' },
  },
  {
    id: 'tsa-life-drawing',
    title: 'Open life drawing at the Toronto School of Art',
    category: 'dropin',
    entry: '$20',
    art: 'art-easel',
    venue: 'Toronto School of Art',
    address: '24 Ryerson Ave, 2nd Floor, Toronto, ON M5T 2P3',
    url: 'https://tsa-art.com/pages/special-programs/life-drawing-without-instruction/',
    source: 'https://tsa-art.com/pages/special-programs/life-drawing-without-instruction/',
    checked: CHECKED,
    description: 'Short poses, a live model, no instruction and no critique — just bring paper. First come, first served, and capped at twenty-four. Sunday parking is free; Monday evening is $6.',
    schedule: [
      { kind: 'weekly', weekday: 0, from: '2026-09-13', to: '2026-12-31', time: '10am–1pm', hour: 10 },
      { kind: 'weekly', weekday: 1, from: '2026-09-14', to: '2026-12-31', time: '6–9pm', hour: 18 },
    ],
  },
  {
    id: 'bad-dog-improv',
    title: 'Beginner improv drop-in',
    category: 'dropin',
    art: 'art-mic',
    entry: '$25 plus HST',
    venue: 'Bad Dog Theatre Company',
    address: '392 Spadina Ave, Unit 2, Toronto, ON M5T 2G7',
    url: 'https://baddogtheatre.com/improv-drop-ins',
    source: 'https://baddogtheatre.com/improv-drop-ins',
    checked: CHECKED,
    description: 'Two hours, no experience, no obligation to ever come back. The lowest-stakes way to find out whether you like doing this in front of people.',
    schedule: { kind: 'weekly', weekday: [1, 6], from: '2026-01-01', to: '2026-12-31', time: '6–8pm', hour: 18 },
  },
  {
    id: 'bike-pirates',
    title: 'Fix your own bike at Bike Pirates',
    category: 'dropin',
    art: 'art-bicycle',
    entry: 'Pay what you can',
    venue: 'Bike Pirates',
    address: '1564 Bloor St W, Toronto, ON M6P 1A4',
    url: 'https://bikepirates.com/',
    source: 'https://bikepirates.com/',
    checked: CHECKED,
    description: 'A volunteer-run DIY workshop: their stands, their tools, their advice, your hands. No appointment — but fill in the waiver on a first visit. You can build a bike from parts if you have the patience.',
    schedule: [
      { kind: 'weekly', weekday: [2, 3], from: '2026-01-01', to: '2026-12-31', time: '6–9pm', hour: 18 },
      { kind: 'weekly', weekday: [6, 0], from: '2026-01-01', to: '2026-12-31', time: '12–4pm', hour: 12 },
    ],
  },
  {
    id: 'tool-library-wednesday',
    title: 'Free makerspace night at the Tool Library',
    category: 'dropin',
    art: 'art-tools',
    entry: 'Free',
    venue: 'Toronto Tool Library and Makerspace',
    address: '192 Spadina Ave, Unit 001, Toronto, ON M5T 2C2',
    url: 'https://ttlmakerspace.com/membership/',
    source: 'https://ttlmakerspace.com/membership/',
    checked: CHECKED,
    description: 'One night a week the makerspace opens to anyone, membership or not — 3D printers, laser cutter, CNC router and a wood shop. Down the alleyway; buzz to be let in.',
    schedule: { kind: 'weekly', weekday: 3, from: '2026-01-01', to: '2026-12-31', time: '7–10pm', hour: 19 },
  },
  {
    id: 'saturday-night-swing',
    title: 'Saturday Night Swing',
    category: 'dropin',
    entry: '$22 at the door, lessons included; $16 students',
    art: 'art-gramophone',
    venue: 'Dovercourt House, second floor',
    address: '805 Dovercourt Rd, Toronto, ON M6H 2X4',
    url: 'https://swingtoronto.com/swing/',
    source: 'https://swingtoronto.com/swing/',
    checked: CHECKED,
    description: 'A live band upstairs at Dovercourt House, with a beginner lesson at six before the dance. Come alone — everyone rotates partners.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-01-01', to: '2026-12-31', time: 'lesson 6pm', hour: 18 },
  },
  {
    id: 'comedy-bar-hot-mic',
    title: 'Comedy Bar\u2019s Hot Mic',
    category: 'comedy',
    entry: '$13',
    art: 'art-neon',
    venue: 'Comedy Bar Danforth, Studio Theatre',
    address: '2800 Danforth Ave, Toronto, ON M4C 1M1',
    url: 'https://comedybar.ca/shows/comedy-bars-hot-mic',
    source: 'https://comedybar.ca/shows/comedy-bars-hot-mic',
    checked: CHECKED,
    description: 'Emerging stand-ups do short sets in the Studio Theatre with a host running the room. Anyone can put their name in the bucket to get on stage, provided they do it by 8:30pm.',
    schedule: { kind: 'weekly', weekday: 2, from: '2026-09-15', to: '2026-12-29', time: '8:30pm', hour: 20 },
  },
  {
    id: 'comedy-bar-studio-mondays',
    title: 'Studio Mondays',
    category: 'comedy',
    entry: '$13',
    art: 'art-neon',
    venue: 'Comedy Bar Danforth, Studio Theatre',
    address: '2800 Danforth Ave, Toronto, ON M4C 1M1',
    url: 'https://comedybar.ca/shows/studio-mondays',
    source: 'https://comedybar.ca/shows/studio-mondays',
    checked: CHECKED,
    description: 'Three improv sets: a longform narrative built from an audience suggestion, a set from a Comedy Bar pro troupe, and the Jim-Jam, a bucket jam anyone can play with no experience. Names in the bucket by 8:30pm.',
    /* Two ranges, not one weekly run: the venue's own schedule skips
       October 12, which is Thanksgiving Monday. */
    schedule: [
      { kind: 'weekly', weekday: 1, from: '2026-09-14', to: '2026-10-05', time: '8:30pm', hour: 20 },
      { kind: 'weekly', weekday: 1, from: '2026-10-19', to: '2026-12-28', time: '8:30pm', hour: 20 },
    ],
  },
];
