/* Listings for "What should we do today?" — Toronto.

   Every entry carries `source` and `checked`: the page the schedule came from
   and the date it was last confirmed. Anything that could not be confirmed
   against a primary source was left out rather than guessed. Re-check before
   the season turns — see README. */

const CHECKED = '2026-09-08';

const CATEGORIES = {
  museum:       { label: 'Museum',            art: 'art-museum'        },
  art:          { label: 'Art & exhibitions', art: 'art-gallery'       },
  market:       { label: 'Farmers’ market',   art: 'art-market'        },
  flea:         { label: 'Flea market',       art: 'art-flea'          },
  books:        { label: 'Books',             art: 'art-books'         },
  architecture: { label: 'Architecture',      art: 'art-architecture'  },
  festival:     { label: 'Festivals',         art: 'art-festival'      },
};

/* schedule kinds
   range  { kind:'range',  start, end }
   day    { kind:'day',    date, time?, hour? }
   weekly { kind:'weekly', weekday, from, to, time?, hour? }
            weekday is 0=Sunday, or an array of them
   nth    { kind:'nth',    weekday, nth, from, to, time?, hour? }
            nth is 1..5, or -1 for the last of the month                */

const EVENTS = [
  /* ------------------------------------------------------------ markets */
  {
    id: 'wychwood-barns',
    title: 'The Stop’s Farmers’ Market',
    category: 'market',
    art: 'art-market',
    venue: 'Artscape Wychwood Barns',
    address: '601 Christie St, Toronto, ON M6G 4C7',
    url: 'https://www.thestop.org/farmersmarket/',
    source: 'https://www.thestop.org/farmersmarket/',
    checked: CHECKED,
    description: 'One of the few markets in the city that runs all year — outdoors along the walkways May to October, inside the main Barn November to April.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-01-01', to: '2026-12-31', time: '8am–1pm', hour: 8 },
  },
  {
    id: 'brick-works',
    title: 'Evergreen Brick Works Farmers Market',
    category: 'market',
    art: 'art-ravine',
    venue: 'Evergreen Brick Works',
    address: '550 Bayview Ave, Toronto, ON M4W 3X8',
    url: 'https://www.evergreen.ca/evergreen-brick-work/activities/saturday-farmers-market/',
    source: 'https://www.evergreen.ca/evergreen-brick-work/activities/saturday-farmers-market/',
    checked: CHECKED,
    description: 'Ontario growers in a former brick factory, snow or shine. Outdoors May to October, indoors from 9am November to April. Walk the ravine trails after.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-01-01', to: '2026-12-31', time: '8am–1pm', hour: 8 },
  },
  {
    id: 'st-lawrence',
    title: 'St. Lawrence Farmers’ Market',
    category: 'market',
    art: 'art-bread',
    venue: 'St. Lawrence Market North',
    address: '92 Front St E, Toronto, ON M5E 1C4',
    url: 'https://www.stlawrencemarket.com/pages/hours_parking/',
    source: 'https://www.stlawrencemarket.com/pages/hours_parking/',
    checked: CHECKED,
    description: 'Farmers have taken the north building on Saturdays since 1803, now in the new hall that opened in 2026. Doors from five in the morning.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-01-01', to: '2026-12-31', time: '5am–3pm', hour: 5 },
  },
  {
    id: 'dufferin-grove',
    title: 'Dufferin Grove Organic Farmers’ Market',
    category: 'market',
    art: 'art-jar',
    venue: 'Dufferin Grove Park Clubhouse',
    address: '875 Dufferin St, Toronto, ON M6H 3L3',
    url: 'https://dufferinpark.ca/market/',
    source: 'https://www.familyfuncanada.com/toronto/outdoor-farmers-markets-toronto/',
    checked: CHECKED,
    description: 'All-organic and year-round, at the clubhouse. Small enough to talk to everyone selling.',
    schedule: { kind: 'weekly', weekday: 4, from: '2026-01-01', to: '2026-12-31', time: '3–7pm', hour: 15 },
  },
  {
    id: 'sorauren',
    title: 'Sorauren Farmers’ Market',
    category: 'market',
    art: 'art-corn',
    venue: 'Sorauren Avenue Park',
    address: '50 Wabash Ave, Toronto, ON M6R 1H8',
    url: 'https://soraurenmarket.com/',
    source: 'https://www.familyfuncanada.com/toronto/outdoor-farmers-markets-toronto/',
    checked: CHECKED,
    description: 'A Monday-evening market in Roncesvalles — dinner from a stall, eaten on the grass while the dog park fills up. Runs to October 26.',
    schedule: { kind: 'weekly', weekday: 1, from: '2026-05-04', to: '2026-10-26', time: '3–7pm', hour: 15 },
  },
  {
    id: 'withrow',
    title: 'Withrow Park Farmers’ Market',
    category: 'market',
    art: 'art-tent',
    venue: 'Withrow Park',
    address: '725 Logan Ave, Toronto, ON M4K 3C7',
    url: 'https://withrowmarket.ca/',
    source: 'https://www.blogto.com/eat_drink/2026/07/9-farmers-markets-toronto-summer/',
    checked: CHECKED,
    description: 'The east end’s Saturday morning ritual, in the shade at the north end of the park. Last market of the season is October 17.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-06-06', to: '2026-10-17', time: '9am–1pm', hour: 9 },
  },
  {
    id: 'trinity-bellwoods-market',
    title: 'Trinity Bellwoods Farmers Market',
    category: 'market',
    art: 'art-market',
    venue: 'Trinity Bellwoods Park, at Dundas and Shaw',
    address: '1053 Dundas St W, Toronto, ON M6J 1W9',
    url: 'https://www.tbfm.ca/',
    source: 'https://www.tbfm.ca/',
    checked: CHECKED,
    description: 'Tuesday afternoons at the Dundas end of the park. Seasonal, and the excuse you needed to stay until dark. Runs to October 27.',
    schedule: { kind: 'weekly', weekday: 2, from: '2026-05-05', to: '2026-10-27', time: '3–7pm', hour: 15 },
  },

  /* ------------------------------------------------------------ museums */
  {
    id: 'ago-first-wednesday',
    title: 'AGO First Wednesday Night Free',
    category: 'museum',
    art: 'art-museum',
    venue: 'Art Gallery of Ontario',
    address: '317 Dundas St W, Toronto, ON M5T 1G4',
    url: 'https://ago.ca/visit/free-wednesday-nights',
    source: 'https://ago.ca/visit/free-wednesday-nights',
    checked: CHECKED,
    description: 'Free admission on the first Wednesday night of the month — not every Wednesday. Tickets are released online at 10am the Monday before, two per person, and they go.',
    schedule: { kind: 'nth', weekday: 3, nth: 1, from: '2026-01-01', to: '2026-12-31', time: '6–9pm', hour: 18 },
  },
  {
    id: 'gardiner-wednesday',
    title: 'Gardiner Museum Free Wednesdays',
    category: 'museum',
    art: 'art-vase',
    venue: 'Gardiner Museum',
    address: '111 Queens Park, Toronto, ON M5S 2C7',
    url: 'https://www.gardinermuseum.on.ca/visit/hours-admission/',
    source: 'https://www.gardinermuseum.on.ca/visit/hours-admission/',
    checked: CHECKED,
    description: 'Free every Wednesday afternoon and evening, no booking needed. Three floors of ceramics across from the ROM, done in an hour. Always free for students, under-18s and Indigenous Peoples.',
    schedule: { kind: 'weekly', weekday: 3, from: '2026-01-01', to: '2026-12-31', time: '4–9pm', hour: 16 },
  },
  {
    id: 'aga-khan-wednesday',
    title: 'BMO Free Wednesdays at the Aga Khan',
    category: 'museum',
    art: 'art-arch',
    venue: 'Aga Khan Museum',
    address: '77 Wynford Dr, North York, ON M3C 1K1',
    url: 'https://agakhanmuseum.org/whats-on/bmo-free-wednesdays/',
    source: 'https://agakhanmuseum.org/whats-on/bmo-free-wednesdays/',
    checked: CHECKED,
    description: 'Free galleries during extended Wednesday hours. Tickets are in person only, at the guest services desk. Worth the trip up for the building and the reflecting pools alone.',
    schedule: { kind: 'weekly', weekday: 3, from: '2026-01-01', to: '2026-12-31', time: '4–8pm', hour: 16 },
  },
  {
    id: 'bata-pwyc',
    title: 'Bata Shoe Museum pay-what-you-can',
    category: 'museum',
    art: 'art-shoe',
    venue: 'Bata Shoe Museum',
    address: '327 Bloor St W, Toronto, ON M5S 1W7',
    url: 'https://batashoemuseum.ca/visit-us/',
    source: 'https://batashoemuseum.ca/visit-us/',
    checked: CHECKED,
    description: 'Thursday evenings are pay-what-you-can. Four and a half thousand years of footwear, which is better than it sounds.',
    schedule: { kind: 'weekly', weekday: 4, from: '2026-01-01', to: '2026-12-31', time: '5–8pm', hour: 17 },
  },
  {
    id: 'bata-free-sunday',
    title: 'Bata Shoe Museum free Sundays',
    category: 'museum',
    art: 'art-lamp',
    venue: 'Bata Shoe Museum',
    address: '327 Bloor St W, Toronto, ON M5S 1W7',
    url: 'https://batashoemuseum.ca/visit-us/',
    source: 'https://batashoemuseum.ca/visit-us/',
    checked: CHECKED,
    description: 'Free for everyone, every Sunday, for the museum’s shorter afternoon hours.',
    schedule: { kind: 'weekly', weekday: 0, from: '2026-01-01', to: '2026-12-31', time: '12–5pm', hour: 12 },
  },

  /* -------------------------------------------------- art & exhibitions */
  {
    id: 'auf-der-maur',
    title: 'Melissa Auf der Maur: My ’90s Rock Photographs',
    category: 'art',
    art: 'art-camera',
    venue: 'Art Gallery of Ontario',
    address: '317 Dundas St W, Toronto, ON M5T 1G4',
    url: 'https://ago.ca/exhibitions/melissa-auf-der-maur-my-90s-rock-photographs',
    source: 'https://ago.ca/press-release/raw-and-contemplative-melissa-auf-der-maur-my-90s-rock-photographs-opens-september-2',
    checked: CHECKED,
    description: 'A backstage pass to the last analogue decade, shot by the Hole and Smashing Pumpkins bassist. Opens to the public today; runs into next summer.',
    schedule: { kind: 'range', start: '2026-09-08', end: '2027-06-30' },
  },
  {
    id: 'sunday-best',
    title: 'Sunday Best: The Power & The Glory of Black Style',
    category: 'art',
    art: 'art-gallery',
    venue: 'Art Gallery of Ontario',
    address: '317 Dundas St W, Toronto, ON M5T 1G4',
    url: 'https://ago.ca/exhibitions/sunday-best-power-glory-black-style',
    source: 'https://ago.ca/press-release/exploring-ritual-and-rebellion-woven-black-style-sunday-best-debuts-ago-fall',
    checked: CHECKED,
    description: 'Ritual and rebellion in Black style and self-fashioning. Members from October 7, passholders October 9, everyone else from October 13.',
    schedule: { kind: 'range', start: '2026-10-13', end: '2027-02-28' },
  },
  {
    id: 'onsite-returning',
    title: 'Returning to Ourselves',
    category: 'art',
    art: 'art-sculpture',
    venue: 'Onsite Gallery, OCAD University',
    address: '199 Richmond St W, Toronto, ON M5V 0H4',
    url: 'https://www.ocadu.ca/galleries/onsite-gallery',
    source: 'https://akimbo.ca/listings/fall-2026-exhibitions-programs-at-onsite-gallery/',
    checked: CHECKED,
    description: 'Forty years of Rebecca Baird and Kenny Alvin Baird, shown alongside work by Inuk artist Michael Massie. Free, and usually empty on a weekday afternoon.',
    schedule: { kind: 'range', start: '2026-09-02', end: '2027-01-30' },
  },
  {
    id: 'image-centre',
    title: 'The Image Centre fall exhibitions',
    category: 'art',
    art: 'art-neon',
    venue: 'The Image Centre, Toronto Metropolitan University',
    address: '33 Gould St, Toronto, ON M5B 1W1',
    url: 'https://theimagecentre.ca/gallery/',
    source: 'https://theimagecentre.ca/visit/',
    checked: CHECKED,
    description: 'The Main and University galleries reopen after installation, with a fall opening reception on September 9, 6–8pm. Free, two minutes from Dundas station.',
    schedule: { kind: 'range', start: '2026-09-09', end: '2026-12-05' },
  },
  {
    id: 'rom-survival',
    title: 'A Story of Survival at the ROM',
    category: 'art',
    art: 'art-fossil',
    venue: 'Royal Ontario Museum',
    address: '100 Queens Park, Toronto, ON M5S 2C6',
    url: 'https://www.rom.on.ca/whats-on/exhibitions',
    source: 'https://www.rom.on.ca/whats-on/exhibitions',
    checked: CHECKED,
    description: 'Closes October 18. The Dawn of Life galleries downstairs are included, and are the better hour anyway.',
    schedule: { kind: 'range', start: '2026-09-08', end: '2026-10-18' },
  },
  {
    id: 'abya-yala',
    title: 'The Allegorical Archipelago of Abya Yala opens',
    category: 'art',
    art: 'art-arch',
    venue: 'Royal Ontario Museum',
    address: '100 Queens Park, Toronto, ON M5S 2C6',
    url: 'https://www.rom.on.ca/whats-on/exhibitions',
    source: 'https://www.rom.on.ca/whats-on/exhibitions',
    checked: CHECKED,
    description: 'Opening day of the ROM’s new fall exhibition. Closing date had not been posted when this was checked.',
    schedule: { kind: 'day', date: '2026-09-26' },
  },
  {
    id: 'moca-fall-opens',
    title: 'MOCA fall season opens',
    category: 'art',
    art: 'art-records',
    venue: 'Museum of Contemporary Art Toronto',
    address: '158 Sterling Rd, Toronto, ON M6R 2B7',
    url: 'https://moca.ca/exhibitions/',
    source: 'https://moca.ca/press-releases/moca-announces-fall-2026-exhibition-details/',
    checked: CHECKED,
    description: 'Bharti Kher and Delcy Morelos, with Beverly Glenn-Copeland’s Light of the Heavens, across two floors of a converted aluminium factory. Free for anyone twenty-five and under.',
    schedule: { kind: 'day', date: '2026-10-04' },
  },
  {
    id: 'nuit-blanche',
    title: 'Nuit Blanche Toronto',
    category: 'art',
    art: 'art-star',
    venue: 'Across the city',
    address: 'Nathan Phillips Square, 100 Queen St W, Toronto, ON M5H 2N2',
    url: 'https://nbto.com/',
    source: 'https://www.destinationontario.com/en-ca/articles/guide-toronto-nuit-blanche',
    checked: CHECKED,
    description: 'Free contemporary art from 7pm to 7am. Pick one neighbourhood and walk it properly instead of chasing the map.',
    schedule: { kind: 'day', date: '2026-10-03', time: '7pm–7am', hour: 19 },
  },
  {
    id: 'art-toronto',
    title: 'Art Toronto',
    category: 'art',
    art: 'art-filmreel',
    venue: 'Metro Toronto Convention Centre',
    address: '255 Front St W, Toronto, ON M5V 2W6',
    url: 'https://arttoronto.ca/home/',
    source: 'https://arttoronto.ca/home/',
    checked: CHECKED,
    description: 'The country’s art fair. A day pass runs past twenty dollars, but it is the entire scene in one room.',
    schedule: { kind: 'range', start: '2026-10-29', end: '2026-11-01' },
  },

  /* --------------------------------------------------------------- flea */
  {
    id: 'toronto-flea',
    title: 'Toronto Flea',
    category: 'flea',
    art: 'art-flea',
    venue: 'Ashbridge Estate',
    address: '1444 Queen St E, Toronto, ON M4L 1E1',
    url: 'https://artsmarket.ca/toronto-flea/',
    source: 'https://festmore.com/events/leslieville-flea-market-toronto-2026',
    checked: CHECKED,
    description: 'Formerly the Leslieville Flea. Furniture, records and mid-century everything on the lawn of a two-hundred-year-old farmhouse. Last Sunday of the season is October 4.',
    schedule: { kind: 'weekly', weekday: 0, from: '2026-05-03', to: '2026-10-04', time: '11am–5pm', hour: 11 },
  },
  {
    id: 'kensington-pedestrian-sundays',
    title: 'Pedestrian Sundays in Kensington',
    category: 'flea',
    art: 'art-lantern',
    venue: 'Kensington Market',
    address: 'Augusta Ave & Baldwin St, Toronto, ON M5T 2L7',
    url: 'https://www.pskensington.ca/',
    source: 'https://www.todocanada.ca/city/toronto/event/pedestrian-sundays-kensington-market/',
    checked: CHECKED,
    description: 'Cars out, everyone else in: drum circles, stoop sales, and the market at its loudest. Augusta stays closed to 10pm. Last Sunday of the month, May to October.',
    schedule: { kind: 'nth', weekday: 0, nth: -1, from: '2026-05-01', to: '2026-10-31', time: '12–7pm', hour: 12 },
  },
  {
    id: 'toronto-vintage-show',
    title: 'Toronto Vintage Show',
    category: 'flea',
    art: 'art-shoe',
    venue: 'Queen Elizabeth Building, Exhibition Place',
    address: '190 Princes’ Blvd, Toronto, ON M6K 3C3',
    url: 'https://www.torontovintageshow.ca/',
    source: 'https://www.explace.on.ca/event/toronto-vintage-show-fall-2026/',
    checked: CHECKED,
    description: 'Dealers of vintage clothing, textiles and antiques under one roof. Saturday 9am–6pm, Sunday 10am–5pm.',
    schedule: { kind: 'range', start: '2026-09-26', end: '2026-09-27' },
  },
  {
    id: 'one-of-a-kind',
    title: 'One of a Kind Christmas Show',
    category: 'flea',
    art: 'art-tree',
    venue: 'Enercare Centre, Exhibition Place',
    address: '100 Princes’ Blvd, Toronto, ON M6K 3C3',
    url: 'https://oneofakindshow.com/home/2026-christmas-show/',
    source: 'https://oneofakindshow.com/home/2026-christmas-show/',
    checked: CHECKED,
    description: 'Hundreds of Canadian makers in one hall for ten days. Every present you owe anyone, solved in an afternoon.',
    schedule: { kind: 'range', start: '2026-11-27', end: '2026-12-06' },
  },

  /* -------------------------------------------------------------- books */
  {
    id: 'word-on-the-street',
    title: 'The Word On The Street',
    category: 'books',
    art: 'art-books',
    venue: 'David Pecaut Square',
    address: '55 John St, Toronto, ON M5V 3G4',
    url: 'https://toronto.thewordonthestreet.ca/',
    source: 'https://toronto.thewordonthestreet.ca/event-directory/annual-festival/2026-festival/',
    checked: CHECKED,
    description: 'Canada’s largest literary festival, free, over two days — small presses, magazine tables, and authors reading in tents. Its 37th year.',
    schedule: { kind: 'range', start: '2026-09-26', end: '2026-09-27' },
  },
  {
    id: 'tifa',
    title: 'Toronto International Festival of Authors',
    category: 'books',
    art: 'art-mic',
    venue: 'Victoria University, University of Toronto',
    address: '91 Charles St W, Toronto, ON M5S 1K7',
    url: 'https://festivalofauthors.ca/festival/',
    source: 'https://festivalofauthors.ca/2026/03/05/2026-festival-dates/',
    checked: CHECKED,
    description: 'Readings and on-stage interviews over five days. Moved off the Harbourfront campus to Victoria University — check the venue on your ticket.',
    schedule: { kind: 'range', start: '2026-10-28', end: '2026-11-01' },
  },

  /* ------------------------------------------------------- architecture */
  {
    id: 'tsa-downtown-yonge',
    title: 'Free architectural walking tours',
    category: 'architecture',
    art: 'art-architecture',
    venue: 'Toronto Society of Architects, Downtown Yonge',
    address: 'Yonge St & Dundas St, Toronto, ON M5B 1R8',
    url: 'https://torontosocietyofarchitects.ca/tours/',
    source: 'https://nowtoronto.com/event/free-architectural-walking-tours/',
    checked: CHECKED,
    description: 'Architect-led walks through Downtown Yonge, free, through to October 24. The society’s nine thematic tours elsewhere in the city are $15 and run 90 to 120 minutes.',
    schedule: { kind: 'range', start: '2026-07-12', end: '2026-10-24' },
  },
  {
    id: 'spadina-museum',
    title: 'Spadina Museum house tour',
    category: 'architecture',
    art: 'art-house',
    venue: 'Spadina Museum',
    address: '285 Spadina Rd, Toronto, ON M5R 2V5',
    url: 'https://www.toronto.ca/explore-enjoy/history-art-culture/museums/spadina-museum/',
    source: 'https://www.toronto.ca/explore-enjoy/history-art-culture/museums/spadina-museum/',
    checked: CHECKED,
    description: 'Admission is free and the house is by guided tour only — hourly from 11:15am, last one at 4. Open Wednesday to Sunday; the grounds are yours either way.',
    schedule: { kind: 'weekly', weekday: [6, 0], from: '2026-01-01', to: '2026-12-31', time: '11am–5pm', hour: 11 },
  },
  {
    id: 'fort-york',
    title: 'Fort York National Historic Site',
    category: 'architecture',
    art: 'art-cannon',
    venue: 'Fort York National Historic Site',
    address: '250 Fort York Blvd, Toronto, ON M5V 3K9',
    url: 'https://www.toronto.ca/explore-enjoy/history-art-culture/museums/fort-york-national-historic-site/',
    source: 'https://www.toronto.ca/explore-enjoy/history-art-culture/museums/fort-york-national-historic-site/',
    checked: CHECKED,
    description: 'The city’s oldest buildings, marooned under the Gardiner. Open Wednesday to Sunday; musket demonstrations at 11:30, 1:30 and 3:30, weather permitting.',
    schedule: { kind: 'weekly', weekday: [6, 0], from: '2026-01-01', to: '2026-12-31', time: '10am–5pm', hour: 10 },
  },
  {
    id: 'bentway-summer-trail',
    title: 'The Bentway Skate Trail',
    category: 'architecture',
    art: 'art-skates',
    venue: 'The Bentway',
    address: '250 Fort York Blvd, Toronto, ON M5V 3K9',
    url: 'https://thebentway.ca/',
    source: 'https://curiocity.com/bentway-skating-trail-toronto-open-late-summer/',
    checked: CHECKED,
    description: 'The 220-metre figure-eight threaded between the columns of the Gardiner, open for the rest of the summer season. Closes September 27; the ice returns near Christmas.',
    schedule: { kind: 'range', start: '2026-08-07', end: '2026-09-27' },
  },

  /* ---------------------------------------------------------- festivals */
  {
    id: 'tiff',
    title: 'Toronto International Film Festival',
    category: 'festival',
    art: 'art-tent',
    venue: 'TIFF Lightbox and King Street West',
    address: '350 King St W, Toronto, ON M5V 3X5',
    url: 'https://tiff.net/',
    source: 'https://en.wikipedia.org/wiki/2026_Toronto_International_Film_Festival',
    checked: CHECKED,
    description: 'The 51st festival: 293 films, King Street closed, and a full film market for the first time. Rush tickets are the only sane way in.',
    schedule: { kind: 'range', start: '2026-09-10', end: '2026-09-20' },
  },
  {
    id: 'cabbagetown-festival',
    title: 'Cabbagetown Festival',
    category: 'festival',
    art: 'art-corn',
    venue: 'Parliament Street',
    address: 'Parliament St & Carlton St, Toronto, ON M5A 2Z1',
    url: 'https://www.cabbagetownto.com/',
    source: 'https://curiocity.com/toronto-cabbagetown-festival/',
    checked: CHECKED,
    description: 'Toronto’s longest-running street festival, through the Victorian half of the east end. Saturday 11am–8pm, Sunday 11am–7pm.',
    schedule: { kind: 'range', start: '2026-09-12', end: '2026-09-13' },
  },
  {
    id: 'ukrainian-festival',
    title: 'Toronto Ukrainian Festival',
    category: 'festival',
    art: 'art-festival',
    venue: 'Bloor West Village',
    address: 'Bloor St W & Jane St, Toronto, ON M6S 1M9',
    url: 'https://ukrainianfestival.com/',
    source: 'https://ukrainianfestival.com/',
    checked: CHECKED,
    description: 'The largest Ukrainian street festival in North America, along Bloor West. Go for the varenyky, stay for the dancing.',
    schedule: { kind: 'range', start: '2026-09-18', end: '2026-09-20' },
  },
  {
    id: 'santa-claus-parade',
    title: 'The Original Santa Claus Parade',
    category: 'festival',
    art: 'art-lantern',
    venue: 'Bloor Street to St. Lawrence Market',
    address: 'Bloor St W & Christie St, Toronto, ON M6G 1M1',
    url: 'https://www.thesantaclausparade.com/the-parade',
    source: 'https://www.thesantaclausparade.com/the-parade',
    checked: CHECKED,
    unconfirmed: 'The 2026 date was not posted when this was checked — November 22 is the traditional third Sunday.',
    description: 'Running since 1905 and free from any curb on the route. Stand north of Bloor if you want to see anything.',
    schedule: { kind: 'day', date: '2026-11-22' },
  },
  {
    id: 'cavalcade-of-lights',
    title: 'Cavalcade of Lights opening night',
    category: 'festival',
    art: 'art-star',
    venue: 'Nathan Phillips Square',
    address: '100 Queen St W, Toronto, ON M5H 2N2',
    url: 'https://www.toronto.ca/explore-enjoy/festivals-events/cavalcade-of-lights/',
    source: 'https://www.toronto.ca/news/cavalcade-of-lights-returns-tomorrow-to-brighten-nathan-phillips-square/',
    checked: CHECKED,
    description: 'Live music from 6pm, the official tree lit at 6:30, and the rink opens. Free. The lights stay on nightly until 11pm through to January 7.',
    schedule: { kind: 'day', date: '2026-11-29', time: 'from 6pm', hour: 18 },
  },
  {
    id: 'distillery-winter-village',
    title: 'Distillery Winter Village',
    category: 'festival',
    art: 'art-jar',
    venue: 'Distillery Historic District',
    address: '55 Mill St, Toronto, ON M5A 3C4',
    url: 'https://thedistillerywintervillage.com/',
    source: 'https://thedistillerywintervillage.com/',
    checked: CHECKED,
    description: 'Cobblestones, a very large tree lit on opening night at 6pm, and mulled wine at a markup. Runs to January 3 — go on a weekday.',
    schedule: { kind: 'range', start: '2026-11-12', end: '2027-01-03' },
  },
];
