/* Seed data for "What should we do today?" — Toronto.
   Dates are placeholders for the 2026 season: check the venue before you go. */

const CATEGORIES = {
  museum:       { label: 'Museum',           art: 'art-museum'       },
  art:          { label: 'Art & exhibitions', art: 'art-gallery'     },
  market:       { label: 'Farmers’ market',  art: 'art-market'       },
  flea:         { label: 'Flea market',       art: 'art-flea'        },
  books:        { label: 'Books',             art: 'art-books'       },
  architecture: { label: 'Architecture',      art: 'art-architecture'},
  festival:     { label: 'Festivals',         art: 'art-festival'    },
};

/* schedule kinds
   range  { kind:'range',  start, end }
   day    { kind:'day',    date, time?, hour? }
   weekly { kind:'weekly', weekday, from, to, time?, hour? }      weekday: 0 = Sunday
   nth    { kind:'nth',    weekday, nth, from, to, time?, hour? } nth: 1..5, -1 = last  */

const EVENTS = [
  /* ---------------------------------------------------------- markets */
  {
    id: 'wychwood-barns',
    title: 'Wychwood Barns Farmers Market',
    category: 'market',
    art: 'art-market',
    venue: 'Artscape Wychwood Barns',
    address: '601 Christie St, Toronto, ON M6G 4C7',
    url: 'https://thestop.org/what-we-do/farmers-market/',
    description: 'The best Saturday market in the city, under the old streetcar barns. Coffee, sourdough, and a great many dogs.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-01-01', to: '2026-12-31', time: '8am–12pm', hour: 8 },
  },
  {
    id: 'brick-works',
    title: 'Evergreen Brick Works Farmers Market',
    category: 'market',
    art: 'art-ravine',
    venue: 'Evergreen Brick Works',
    address: '550 Bayview Ave, Toronto, ON M4W 3X8',
    url: 'https://www.evergreen.ca/evergreen-brick-works/farmers-market/',
    description: 'Ontario growers in a former brick factory at the bottom of the Don Valley. Go early, then walk the ravine trails behind it.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-01-01', to: '2026-12-31', time: '8am–1pm', hour: 8 },
  },
  {
    id: 'st-lawrence',
    title: 'St. Lawrence Farmers’ Market',
    category: 'market',
    art: 'art-bread',
    venue: 'St. Lawrence Market North',
    address: '92 Front St E, Toronto, ON M5E 1C4',
    url: 'https://www.stlawrencemarket.com/markets/farmers-market',
    description: 'Farmers have taken the north building on Saturdays since 1803. The peameal sandwich is across the street in the south.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-01-01', to: '2026-12-31', time: '5am–3pm', hour: 5 },
  },
  {
    id: 'dufferin-grove',
    title: 'Dufferin Grove Organic Farmers Market',
    category: 'market',
    art: 'art-jar',
    venue: 'Dufferin Grove Park',
    address: '875 Dufferin St, Toronto, ON M6H 3L3',
    url: 'https://dufferinpark.ca/market/',
    description: 'All-organic, year-round, and small enough to talk to everyone selling. Moves indoors once it turns cold.',
    schedule: { kind: 'weekly', weekday: 4, from: '2026-01-01', to: '2026-12-31', time: '3–7pm', hour: 15 },
  },
  {
    id: 'sorauren',
    title: 'Sorauren Park Farmers Market',
    category: 'market',
    art: 'art-market',
    venue: 'Sorauren Avenue Park',
    address: '289 Sorauren Ave, Toronto, ON M6R 2G2',
    url: 'https://soraurenmarket.com/',
    description: 'A Monday-evening market in Roncesvalles — dinner from a stall, eaten on the grass while the dog park fills up.',
    schedule: { kind: 'weekly', weekday: 1, from: '2026-01-01', to: '2026-12-31', time: '3–7pm', hour: 15 },
  },
  {
    id: 'withrow',
    title: 'Withrow Park Farmers Market',
    category: 'market',
    art: 'art-corn',
    venue: 'Withrow Park',
    address: '725 Logan Ave, Toronto, ON M4K 3C7',
    url: 'https://withrowmarket.com/',
    description: 'The east end’s Saturday morning ritual, in the shade at the north end of the park. Outdoor season only.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-05-02', to: '2026-10-31', time: '9am–1pm', hour: 9 },
  },
  {
    id: 'trinity-bellwoods-market',
    title: 'Trinity Bellwoods Farmers Market',
    category: 'market',
    art: 'art-market',
    venue: 'Trinity Bellwoods Park',
    address: '790 Queen St W, Toronto, ON M6J 1G3',
    url: 'https://trinitybellwoodsfarmersmarket.ca/',
    description: 'Tuesday afternoons along the path off Dundas. Small, seasonal, and the excuse you needed to sit in the park until dark.',
    schedule: { kind: 'weekly', weekday: 2, from: '2026-06-02', to: '2026-10-27', time: '3–7pm', hour: 15 },
  },

  /* ----------------------------------------------------------- museums */
  {
    id: 'ago-wednesday',
    title: 'AGO Free Wednesday Nights',
    category: 'museum',
    art: 'art-museum',
    venue: 'Art Gallery of Ontario',
    address: '317 Dundas St W, Toronto, ON M5T 1G4',
    url: 'https://ago.ca/',
    description: 'General admission is free on Wednesday evenings. Book the timed pass early in the week — they go.',
    schedule: { kind: 'weekly', weekday: 3, from: '2026-01-01', to: '2026-12-31', time: '6–9pm', hour: 18 },
  },
  {
    id: 'gardiner-wednesday',
    title: 'Gardiner Museum Free Wednesday Nights',
    category: 'museum',
    art: 'art-vase',
    venue: 'Gardiner Museum',
    address: '111 Queens Park, Toronto, ON M5S 2C7',
    url: 'https://www.gardinermuseum.on.ca/',
    description: 'Three floors of ceramics across from the ROM, free on Wednesday evenings. Quiet, small, done in an hour.',
    schedule: { kind: 'weekly', weekday: 3, from: '2026-01-01', to: '2026-12-31', time: '4–9pm', hour: 16 },
  },
  {
    id: 'aga-khan-wednesday',
    title: 'Aga Khan Museum Free Wednesdays',
    category: 'museum',
    art: 'art-arch',
    venue: 'Aga Khan Museum',
    address: '77 Wynford Dr, North York, ON M3C 1K1',
    url: 'https://www.agakhanmuseum.org/',
    description: 'Free admission on Wednesday afternoons. Worth the trip up to Eglinton for the building and the reflecting pools alone.',
    schedule: { kind: 'weekly', weekday: 3, from: '2026-01-01', to: '2026-12-31', time: '4–8pm', hour: 16 },
  },
  {
    id: 'bata-pwyc',
    title: 'Bata Shoe Museum pay-what-you-can',
    category: 'museum',
    art: 'art-shoe',
    venue: 'Bata Shoe Museum',
    address: '327 Bloor St W, Toronto, ON M5S 1W7',
    url: 'https://batashoemuseum.ca/',
    description: 'Thursday evenings are pay-what-you-can. Four and a half thousand years of footwear, which is better than it sounds.',
    schedule: { kind: 'weekly', weekday: 4, from: '2026-01-01', to: '2026-12-31', time: '5–8pm', hour: 17 },
  },

  /* ------------------------------------------------ art & exhibitions */
  {
    id: 'power-plant-fall',
    title: 'The Power Plant fall exhibitions',
    category: 'art',
    art: 'art-sculpture',
    venue: 'The Power Plant Contemporary Art Gallery',
    address: '231 Queens Quay W, Toronto, ON M5J 2G8',
    url: 'https://thepowerplant.org/',
    description: 'Three new shows across the whole building for the fall season. Admission is always free, which still feels like a mistake in their favour.',
    schedule: { kind: 'range', start: '2026-09-05', end: '2026-12-20' },
  },
  {
    id: 'moca-fall',
    title: 'MOCA Toronto fall season',
    category: 'art',
    art: 'art-neon',
    venue: 'Museum of Contemporary Art Toronto',
    address: '158 Sterling Rd, Toronto, ON M6R 2B7',
    url: 'https://moca.ca/',
    description: 'Two floors of a converted aluminium factory in the Junction Triangle. Free for anyone twenty-five and under.',
    schedule: { kind: 'range', start: '2026-09-08', end: '2026-11-29' },
  },
  {
    id: 'ago-fall-show',
    title: 'AGO fall special exhibition',
    category: 'art',
    art: 'art-gallery',
    venue: 'Art Gallery of Ontario',
    address: '317 Dundas St W, Toronto, ON M5T 1G4',
    url: 'https://ago.ca/exhibitions',
    description: 'The big ticketed show of the season. An annual pass costs about what two visits do, so do the arithmetic at the door.',
    schedule: { kind: 'range', start: '2026-09-26', end: '2027-01-10' },
  },
  {
    id: 'rom-fall-show',
    title: 'ROM fall special exhibition',
    category: 'art',
    art: 'art-fossil',
    venue: 'Royal Ontario Museum',
    address: '100 Queens Park, Toronto, ON M5S 2C6',
    url: 'https://www.rom.on.ca/en/exhibitions-galleries',
    description: 'Closes at the start of November. The Dawn of Life galleries downstairs are included, and are the better hour anyway.',
    schedule: { kind: 'range', start: '2026-09-08', end: '2026-11-01' },
  },
  {
    id: 'onsite-ocad',
    title: 'Onsite Gallery at OCAD U',
    category: 'art',
    art: 'art-neon',
    venue: 'Onsite Gallery',
    address: '199 Richmond St W, Toronto, ON M5V 0H4',
    url: 'https://www2.ocadu.ca/onsite',
    description: 'OCAD’s free public gallery on Richmond. Small, sharp, and usually empty on a weekday afternoon.',
    schedule: { kind: 'range', start: '2026-09-16', end: '2026-12-06' },
  },
  {
    id: 'image-centre',
    title: 'Toronto Metropolitan Image Centre',
    category: 'art',
    art: 'art-camera',
    venue: 'TMU Image Centre',
    address: '33 Gould St, Toronto, ON M5B 1W1',
    url: 'https://www.torontomu.ca/ric/',
    description: 'Photography drawn from the Black Star collection and elsewhere. Free, and two minutes from Dundas station.',
    schedule: { kind: 'range', start: '2026-09-09', end: '2026-12-05' },
  },
  {
    id: 'nuit-blanche',
    title: 'Nuit Blanche Toronto',
    category: 'art',
    art: 'art-star',
    venue: 'Across the city',
    address: 'Nathan Phillips Square, 100 Queen St W, Toronto, ON M5H 2N2',
    url: 'https://nbto.com/',
    description: 'Free contemporary art from sunset to sunrise. Pick one neighbourhood and walk it properly instead of chasing the map.',
    schedule: { kind: 'day', date: '2026-10-03', time: '7pm–7am', hour: 19 },
  },
  {
    id: 'art-toronto',
    title: 'Art Toronto',
    category: 'art',
    art: 'art-sculpture',
    venue: 'Metro Toronto Convention Centre',
    address: '255 Front St W, Toronto, ON M5V 2W6',
    url: 'https://arttoronto.ca/',
    description: 'The country’s big art fair. A day pass runs past twenty dollars, but it is the entire scene in one room.',
    schedule: { kind: 'range', start: '2026-10-23', end: '2026-10-25' },
  },

  /* ------------------------------------------------------------ fleas */
  {
    id: 'junction-flea',
    title: 'Junction Flea',
    category: 'flea',
    art: 'art-flea',
    venue: 'The Junction',
    address: 'Dundas St W & Pacific Ave, Toronto, ON M6P 3Y5',
    url: 'https://www.thejunctionflea.com/',
    description: 'Vintage dealers and makers behind Dundas West. Cash helps; so does turning up in the first hour.',
    schedule: { kind: 'nth', weekday: 0, nth: 3, from: '2026-05-01', to: '2026-10-31', time: '10am–5pm', hour: 10 },
  },
  {
    id: 'leslieville-flea',
    title: 'Leslieville Flea',
    category: 'flea',
    art: 'art-records',
    venue: 'Ashbridge Estate',
    address: '1444 Queen St E, Toronto, ON M4L 1E1',
    url: 'https://leslievilleflea.com/',
    description: 'Furniture, records and mid-century everything on the lawn of a two-hundred-year-old farmhouse.',
    schedule: { kind: 'nth', weekday: 0, nth: 1, from: '2026-05-01', to: '2026-11-30', time: '10am–4pm', hour: 10 },
  },
  {
    id: 'kensington-pedestrian-sundays',
    title: 'Pedestrian Sundays in Kensington',
    category: 'flea',
    art: 'art-lamp',
    venue: 'Kensington Market',
    address: 'Augusta Ave & Baldwin St, Toronto, ON M5T 2L7',
    url: 'https://www.pskensington.ca/',
    description: 'Cars out, everyone else in: drum circles, stoop sales, and the market at its loudest. Last Sunday of the month.',
    schedule: { kind: 'nth', weekday: 0, nth: -1, from: '2026-05-01', to: '2026-10-31', time: '12–7pm', hour: 12 },
  },
  {
    id: 'vintage-clothing-show',
    title: 'Toronto Vintage Clothing Show',
    category: 'flea',
    art: 'art-shoe',
    venue: 'Queen Elizabeth Building, Exhibition Place',
    address: '190 Princes’ Blvd, Toronto, ON M6K 3C3',
    url: 'https://www.torontovintageclothingshow.com/',
    description: 'Ninety-odd dealers of vintage clothing and textiles under one roof. The November one is the bigger of the two.',
    schedule: { kind: 'day', date: '2026-11-22', time: '10am–5pm', hour: 10 },
  },
  {
    id: 'one-of-a-kind',
    title: 'One of a Kind Show',
    category: 'flea',
    art: 'art-jar',
    venue: 'Enercare Centre, Exhibition Place',
    address: '100 Princes’ Blvd, Toronto, ON M6K 3C3',
    url: 'https://oneofakindshow.com/toronto/',
    description: 'Eight hundred Canadian makers in one hall for eleven days. Every present you owe anyone, solved in an afternoon.',
    schedule: { kind: 'range', start: '2026-11-26', end: '2026-12-06' },
  },

  /* ------------------------------------------------------------ books */
  {
    id: 'word-on-the-street',
    title: 'Word On The Street',
    category: 'books',
    art: 'art-books',
    venue: 'Queen’s Park',
    address: '110 Wellesley St W, Toronto, ON M7A 1A2',
    url: 'https://thewordonthestreet.ca/toronto/',
    description: 'A free book festival across Queen’s Park — small presses, magazine tables, and authors reading in tents.',
    schedule: { kind: 'day', date: '2026-09-27', time: '11am–6pm', hour: 11 },
  },
  {
    id: 'ifoa',
    title: 'International Festival of Authors',
    category: 'books',
    art: 'art-mic',
    venue: 'Harbourfront Centre',
    address: '235 Queens Quay W, Toronto, ON M5J 2G8',
    url: 'https://ifoa.org/',
    description: 'Ten days of readings and on-stage interviews down at the lake. Individual tickets are cheap; students cheaper.',
    schedule: { kind: 'range', start: '2026-10-22', end: '2026-11-01' },
  },
  {
    id: 'td-gallery',
    title: 'TD Gallery at the Reference Library',
    category: 'books',
    art: 'art-gallery',
    venue: 'Toronto Reference Library',
    address: '789 Yonge St, Toronto, ON M4W 2G8',
    url: 'https://www.torontopubliclibrary.ca/',
    description: 'A free exhibition on the ground floor, then the atrium upstairs for the rest of the afternoon.',
    schedule: { kind: 'range', start: '2026-09-12', end: '2026-12-13' },
  },

  /* ---------------------------------------------------- architecture */
  {
    id: 'tsa-walks',
    title: 'Toronto Society of Architects walking tour',
    category: 'architecture',
    art: 'art-architecture',
    venue: 'Toronto Society of Architects',
    address: 'Toronto City Hall, 100 Queen St W, Toronto, ON M5H 2N2',
    url: 'https://www.torontosocietyofarchitects.ca/tours/',
    description: 'Architect-led walks through a single neighbourhood. Saturdays until the weather ends it.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-05-01', to: '2026-10-31', time: '10am–12pm', hour: 10 },
  },
  {
    id: 'spadina-museum',
    title: 'Spadina Museum house tour',
    category: 'architecture',
    art: 'art-house',
    venue: 'Spadina Museum',
    address: '285 Spadina Rd, Toronto, ON M5R 2V5',
    url: 'https://www.toronto.ca/explore-enjoy/history-art-culture/museums/spadina-museum/',
    description: 'A 1900s house frozen mid-century, next door to Casa Loma and a fraction of the price.',
    schedule: { kind: 'weekly', weekday: 0, from: '2026-01-01', to: '2026-12-31', time: '12–5pm', hour: 12 },
  },
  {
    id: 'fort-york',
    title: 'Fort York guided tour',
    category: 'architecture',
    art: 'art-cannon',
    venue: 'Fort York National Historic Site',
    address: '250 Fort York Blvd, Toronto, ON M5V 3K9',
    url: 'https://www.toronto.ca/explore-enjoy/history-art-culture/museums/fort-york/',
    description: 'The city’s oldest buildings, marooned under the Gardiner. The tour is the only way to get inside the barracks.',
    schedule: { kind: 'weekly', weekday: 6, from: '2026-01-01', to: '2026-12-31', time: '11am–4pm', hour: 11 },
  },
  {
    id: 'bentway-skate-trail',
    title: 'The Bentway Skate Trail opens',
    category: 'architecture',
    art: 'art-skates',
    venue: 'The Bentway',
    address: '250 Fort York Blvd, Toronto, ON M5V 3K9',
    url: 'https://thebentway.ca/',
    description: 'A figure-eight of ice threaded between the columns of the Gardiner Expressway. Free, floodlit, rentals on site.',
    schedule: { kind: 'day', date: '2026-12-05', time: 'from 10am', hour: 10 },
  },

  /* -------------------------------------------------------- festivals */
  {
    id: 'tiff',
    title: 'Toronto International Film Festival',
    category: 'festival',
    art: 'art-filmreel',
    venue: 'TIFF Lightbox and King Street West',
    address: '350 King St W, Toronto, ON M5V 3X5',
    url: 'https://tiff.net/',
    description: 'King Street closes and the city pretends to be Cannes for ten days. Rush tickets are the only sane way in.',
    schedule: { kind: 'range', start: '2026-09-10', end: '2026-09-20' },
  },
  {
    id: 'cabbagetown-festival',
    title: 'Cabbagetown Festival',
    category: 'festival',
    art: 'art-tent',
    venue: 'Parliament Street',
    address: 'Parliament St & Carlton St, Toronto, ON M5A 2Z1',
    url: 'https://www.oldcabbagetown.com/cabbagetown-festival/',
    description: 'A street fair through the Victorian half of the east end — a parade, a corn roast, and far too many patio pints.',
    schedule: { kind: 'range', start: '2026-09-12', end: '2026-09-13' },
  },
  {
    id: 'ukrainian-festival',
    title: 'Toronto Ukrainian Festival',
    category: 'festival',
    art: 'art-festival',
    venue: 'Bloor West Village',
    address: 'Bloor St W & Jane St, Toronto, ON M6S 1M9',
    url: 'https://www.ukrainianfestival.com/',
    description: 'The largest Ukrainian street festival in North America. Go for the varenyky, stay for the dancing.',
    schedule: { kind: 'range', start: '2026-09-18', end: '2026-09-20' },
  },
  {
    id: 'santa-claus-parade',
    title: 'Original Santa Claus Parade',
    category: 'festival',
    art: 'art-lantern',
    venue: 'Bloor Street to St. Lawrence Market',
    address: 'Bloor St W & Christie St, Toronto, ON M6G 1M1',
    url: 'https://thesantaclausparade.ca/',
    description: 'Running since 1905, free from any curb on the route. Stand north of Bloor if you want to see anything.',
    schedule: { kind: 'day', date: '2026-11-15', time: '12:30–3pm', hour: 12 },
  },
  {
    id: 'cavalcade-of-lights',
    title: 'Cavalcade of Lights',
    category: 'festival',
    art: 'art-star',
    venue: 'Nathan Phillips Square',
    address: '100 Queen St W, Toronto, ON M5H 2N2',
    url: 'https://www.toronto.ca/explore-enjoy/festivals-events/cavalcade-of-lights/',
    description: 'The square’s tree goes on, there are fireworks, and the rink opens for the season. Free.',
    schedule: { kind: 'day', date: '2026-11-28', time: '6–10pm', hour: 18 },
  },
  {
    id: 'christmas-market',
    title: 'Distillery Winter Village',
    category: 'festival',
    art: 'art-tree',
    venue: 'Distillery Historic District',
    address: '55 Mill St, Toronto, ON M5A 3C4',
    url: 'https://www.distillerywintervillage.com/',
    description: 'Cobblestones, a very large tree, and mulled wine at a markup. Free on weekdays, ticketed on weekends — go on a Tuesday.',
    schedule: { kind: 'range', start: '2026-11-12', end: '2026-12-23' },
  },
  {
    id: 'winter-solstice',
    title: 'Kensington Market Winter Solstice',
    category: 'festival',
    art: 'art-lantern',
    venue: 'Kensington Market',
    address: 'Augusta Ave & Oxford St, Toronto, ON M5T 2L7',
    url: 'https://www.redpepperspectacle.com/',
    description: 'A lantern parade through the market on the longest night, ending with a fire in Alexandra Park. The best night of the year.',
    schedule: { kind: 'day', date: '2026-12-21', time: 'from 6pm', hour: 18 },
  },
];
