/* Generated by scrape/run.mjs — do not edit by hand.
   Hand-written listings live in data.js; these are polled from the sources
   in scrape/sources.mjs and merged at load. */

const SCRAPED = [
  {
    "id": "baddog-sweet-sweet-friends-2026-09-09",
    "title": "Sweet Sweet Friends",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Sweet Action Theatre",
    "address": "180 Shaw Street, Toronto, ON, M6J 2W5, Canada",
    "url": "https://baddogtheatre.com/whats-on",
    "source": "https://baddogtheatre.com/whats-on",
    "checked": "2026-09-09",
    "description": "Listed by Bad Dog Theatre.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-09",
      "time": "7:00 PM – 8:00 PM"
    },
    "scrapedFrom": "baddog",
    "via": "model"
  },
  {
    "id": "baddog-sweet-sweet-friends-2026-09-16",
    "title": "Sweet Sweet Friends",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Sweet Sweet Friends",
    "address": "180 Shaw Street, Toronto, ON, M6J 2W5, Canada",
    "url": "https://baddogtheatre.com/whats-on",
    "source": "https://baddogtheatre.com/whats-on",
    "checked": "2026-09-09",
    "description": "Listed by Bad Dog Theatre.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-16",
      "time": "7:00 PM – 8:00 PM"
    },
    "scrapedFrom": "baddog",
    "via": "model"
  },
  {
    "id": "baddog-sweet-sweet-friends-bad-dog-theatre-company-toro-2026-09-09",
    "title": "Sweet Sweet Friends — Bad Dog Theatre Company - Toronto's Best Improv",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Sweet Action Theatre",
    "address": "180 Shaw Street\nToronto, ON, M6J 2W5\nCanada",
    "url": "https://baddogtheatre.com/whats-on/2026/9/9/sweet-sweet-friends",
    "source": "https://baddogtheatre.com/whats-on/2026/9/9/sweet-sweet-friends",
    "checked": "2026-09-09",
    "description": "Listed by Bad Dog Theatre.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-09"
    },
    "scrapedFrom": "baddog",
    "via": "json-ld"
  },
  {
    "id": "baddog-sweet-sweet-friends-bad-dog-theatre-company-toro-2026-09-16",
    "title": "Sweet Sweet Friends — Bad Dog Theatre Company - Toronto's Best Improv",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Sweet Sweet Friends",
    "address": "180 Shaw Street\nToronto, ON, M6J 2W5\nCanada",
    "url": "https://baddogtheatre.com/whats-on/2026/9/16/sweet-sweet-friends",
    "source": "https://baddogtheatre.com/whats-on/2026/9/16/sweet-sweet-friends",
    "checked": "2026-09-09",
    "description": "Listed by Bad Dog Theatre.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-16"
    },
    "scrapedFrom": "baddog",
    "via": "json-ld"
  },
  {
    "id": "baddog-the-audition-2026-09-11",
    "title": "The Audition",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Comedy Bar Bloor",
    "address": "945 Bloor Street West, Toronto, ON, M6H 1L5, Canada",
    "url": "https://baddogtheatre.com/whats-on",
    "source": "https://baddogtheatre.com/whats-on",
    "checked": "2026-09-09",
    "description": "Listed by Bad Dog Theatre.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11",
      "time": "7:00 PM – 8:00 PM"
    },
    "scrapedFrom": "baddog",
    "via": "model"
  },
  {
    "id": "baddog-the-audition-2026-09-18",
    "title": "The Audition",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Comedy Bar Bloor",
    "address": "945 Bloor Street West, Toronto, ON, M6H 1L5, Canada",
    "url": "https://baddogtheatre.com/whats-on",
    "source": "https://baddogtheatre.com/whats-on",
    "checked": "2026-09-09",
    "description": "Listed by Bad Dog Theatre.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-18",
      "time": "7:00 PM – 8:00 PM"
    },
    "scrapedFrom": "baddog",
    "via": "model"
  },
  {
    "id": "baddog-the-audition-bad-dog-theatre-company-toronto-s-b-2026-09-11",
    "title": "The Audition  — Bad Dog Theatre Company - Toronto's Best Improv",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Comedy Bar Bloor",
    "address": "945 Bloor Street West\nToronto, ON, M6H 1L5\nCanada",
    "url": "https://baddogtheatre.com/whats-on/2026/9/4/the-audition-rz4dm",
    "source": "https://baddogtheatre.com/whats-on/2026/9/4/the-audition-rz4dm",
    "checked": "2026-09-09",
    "description": "Listed by Bad Dog Theatre.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11"
    },
    "scrapedFrom": "baddog",
    "via": "json-ld"
  },
  {
    "id": "baddog-the-bucket-show-2026-09-16",
    "title": "The Bucket Show",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Sweet Action",
    "address": "180 Shaw Street, Unit #106, Toronto, ON, M6J 2W5, Canada",
    "url": "https://baddogtheatre.com/whats-on",
    "source": "https://baddogtheatre.com/whats-on",
    "checked": "2026-09-09",
    "description": "Listed by Bad Dog Theatre.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-16",
      "time": "8:30 PM – 9:30 PM"
    },
    "scrapedFrom": "baddog",
    "via": "model"
  },
  {
    "id": "bentway-artist-talk-with-paul-ram-rez-jonas-2026-09-15",
    "title": "Artist Talk with Paul Ramírez Jonas",
    "category": "architecture",
    "art": "art-skates",
    "venue": "The Bentway",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-09",
    "description": "To mark the Canadian premiere of Public Trust, join acclaimed artist Paul Ramírez Jonas in conversation with The Bentway's Director of Programming Anna Gallagher-Ross about his imaginative body of work and his long-time…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-15"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-artist-talk-with-paul-ram-rez-jonas-2026-09-15",
    "title": "Artist Talk with Paul Ramírez Jonas",
    "category": "architecture",
    "art": "art-skates",
    "entry": "Free",
    "venue": "Toronto Public Library – Fort York Branch",
    "address": "Fort York Boulevard, Toronto, ON, Canada",
    "url": "https://thebentway.ca/event/artist-talk-with-paul-ramirez-jonas/",
    "source": "https://thebentway.ca/event/artist-talk-with-paul-ramirez-jonas/",
    "checked": "2026-09-09",
    "description": "To mark the Canadian premiere of Public Trust, join acclaimed artist Paul Ramírez Jonas in conversation with The Bentway's Director of Programming Anna Gallagher-Ross about his imaginative body of work and his long-time…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-15",
      "time": "6:00 pm – 7:30 pm"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-public-trust-2026-09-15",
    "title": "Public Trust",
    "category": "architecture",
    "art": "art-skates",
    "venue": "The Bentway",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-09",
    "description": "Torontonians are invited to make promises to themselves and their community—not just as inhabitants of the city, but as co-authors of its future…",
    "schedule": {
      "kind": "range",
      "start": "2026-09-15",
      "end": "2026-10-04"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-public-trust-2026-09-15",
    "title": "Public Trust",
    "category": "architecture",
    "art": "art-skates",
    "venue": "The Bentway",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/event/bentway-after-school/",
    "source": "https://thebentway.ca/event/bentway-after-school/",
    "checked": "2026-09-09",
    "description": "Torontonians are invited to make promises to themselves and their community—not just as inhabitants of the city, but as co-authors of its future…",
    "schedule": {
      "kind": "range",
      "start": "2026-09-15",
      "end": "2026-10-04"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-public-trust-2026-09-15",
    "title": "Public Trust",
    "category": "architecture",
    "art": "art-skates",
    "entry": "Free",
    "venue": "Toronto Public Library Fort York branch; Marina Quay West; Harbourfront Centre; The Bentway",
    "address": "Toronto",
    "url": "https://thebentway.ca/event/public-trust/",
    "source": "https://thebentway.ca/event/public-trust/",
    "checked": "2026-09-09",
    "description": "A touring interactive public artwork by Paul Ramírez Jonas consisting of a large-scale marquee and two eight-foot tables with seating, staffed by local performers…",
    "schedule": {
      "kind": "range",
      "start": "2026-09-15",
      "end": "2026-10-04"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-public-trust-2026-09-15",
    "title": "Public Trust",
    "category": "architecture",
    "art": "art-skates",
    "entry": "Free",
    "venue": "Toronto Public Library Fort York branch; Marina Quay West; Harbourfront Centre; The Bentway",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/event/public-trust-toronto-public-library/",
    "source": "https://thebentway.ca/event/public-trust-toronto-public-library/",
    "checked": "2026-09-09",
    "description": "Paul Ramírez Jonas' Public Trust asks participants to examine the value of their word…",
    "schedule": {
      "kind": "range",
      "start": "2026-09-15",
      "end": "2026-10-04"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-public-trust-toronto-public-library-2026-09-15",
    "title": "Public Trust @ Toronto Public Library",
    "category": "architecture",
    "art": "art-skates",
    "venue": "Toronto Public Library",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-09",
    "description": "Torontonians are invited to make promises to themselves and their community—not just as inhabitants of the city, but as co-authors of its future.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-15"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-public-trust-toronto-public-library-fort-york-br-2026-09-15",
    "title": "Public Trust – Toronto Public Library, Fort York branch (International Day of Democracy)",
    "category": "architecture",
    "art": "art-skates",
    "entry": "Free",
    "venue": "Toronto Public Library, Fort York branch",
    "address": "190 Fort York Blvd, Toronto",
    "url": "https://thebentway.ca/event/public-trust/",
    "source": "https://thebentway.ca/event/public-trust/",
    "checked": "2026-09-09",
    "description": "International Day of Democracy presentation of Public Trust, with an Artist Talk with Paul Ramírez Jonas at 6:00pm, free registration.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-15",
      "time": "10:30 am – 5:30 pm"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-roller-skate-lessons-september-11-2026-09-11",
    "title": "Roller Skate Lessons: September 11",
    "category": "architecture",
    "art": "art-skates",
    "venue": "The Bentway",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-09",
    "description": "Learn how to roll with us! This summer, we're offering weekly roller skate lessons for those who are looking to gain basic skills.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-skate-trail-closed-2026-09-12",
    "title": "Skate Trail Closed",
    "category": "architecture",
    "art": "art-skates",
    "venue": "The Bentway",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-09",
    "description": "Listed by The Bentway.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-12"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "comedybar-bloomin-funyuns-2026-09-22",
    "title": "BLOOMIN FUNYUNS",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$25",
    "venue": "Comedy Bar (Cabaret)",
    "address": "945 Bloor Street W, Toronto, ON, M6H 1L5",
    "url": "https://comedybar.ca/shows/bloomin-funyuns",
    "source": "https://comedybar.ca/shows/bloomin-funyuns",
    "checked": "2026-09-09",
    "description": "A show featuring up-and-coming Stand ups from the cbpro comedy school mixed with a couple pros and a pro headliner and a rotating guest host. DGSPECIAL PRODUCTIONS PRESENTS.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-22",
      "time": "08:00 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-chaotic-good-2026-09-18",
    "title": "Chaotic Good",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$25 online, $30 at the door",
    "venue": "Comedy Bar (Bloor St) - Main Stage",
    "address": "945 Bloor Street W, Toronto, ON, M6H 1L5",
    "url": "https://comedybar.ca/shows/chaotic-good",
    "source": "https://comedybar.ca/shows/chaotic-good",
    "checked": "2026-09-09",
    "description": "Chaotic Good is an all pro comedy show showcasing 7 headliners doing their best 7 minutes of material on a show so good, it will feel chaotic!",
    "schedule": {
      "kind": "day",
      "date": "2026-09-18",
      "time": "11:00 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-killer-comics-2026-09-23",
    "title": "KILLER COMICS",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$25 (General Admission listed at $28)",
    "venue": "Comedy Bar West (Cabaret)",
    "address": "945 Bloor Street W, Toronto, ON, M6H 1L5",
    "url": "https://comedybar.ca/shows/killer-comics",
    "source": "https://comedybar.ca/shows/killer-comics",
    "checked": "2026-09-09",
    "description": "Prepare yourself to literally die from laughter after seeing KILLER COMICS - a comedy show curated with a collection of Canada's top KILLER COMICS - this month features Adam Christie, Leonard Chan, Rebecca Reeds…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-23",
      "time": "9:30PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-nice-time-2026-09-30",
    "title": "Nice Time",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$10",
    "venue": "Comedy Bar Bloor (Cabaret)",
    "address": "945 Bloor Street W, Toronto, ON, M6H 1L5",
    "url": "https://comedybar.ca/shows/nice-time-jfl",
    "source": "https://comedybar.ca/shows/nice-time-jfl",
    "checked": "2026-09-09",
    "description": "Toronto's best comedians improvise a brand new hour long show for you every week. Featuring Dan Beirne and Nicole Passmore, and a rotating cast of guest improvisers, with music from Jordan Armstrong.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-30",
      "time": "08:00 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-perfect-10-comedy-2026-09-11",
    "title": "Perfect 10 Comedy",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$28 General Admission",
    "venue": "Comedy Bar (Bloor St) - Cabaret",
    "address": "945 Bloor Street W, Toronto, ON, M6H 1L5",
    "url": "https://comedybar.ca/shows/perfect-10-comedy",
    "source": "https://comedybar.ca/shows/perfect-10-comedy",
    "checked": "2026-09-09",
    "description": "Perfect 10 Comedy a monthly stand-up show featuring four handpicked pro comedians just for you, as seen on Just For Laughs, CBC Comedy, and your nightly doom scrolls. Hosted by Daniel Woodrow.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11",
      "time": "08:30 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-studio-saturdays-2026-09-12",
    "title": "STUDIO SATURDAYS",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$13",
    "venue": "Comedy Bar Danforth - Studio Theatre",
    "address": "2800 Danforth Avenue, Toronto, ON, M4C 1M1",
    "url": "https://comedybar.ca/shows/studio-saturdays",
    "source": "https://comedybar.ca/shows/studio-saturdays",
    "checked": "2026-09-09",
    "description": "Buckle up for scenic and musical improv at its best as our CB PRO students hit the stage and bring the laughs! New characters, scenarios and hilarity that hits all the high notes all inspired by your suggestions!",
    "schedule": {
      "kind": "day",
      "date": "2026-09-12",
      "time": "06:00 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-studio-saturdays-2026-09-19",
    "title": "STUDIO SATURDAYS",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$13",
    "venue": "Comedy Bar Danforth - Studio Theatre",
    "address": "2800 Danforth Avenue, Toronto, ON, M4C 1M1",
    "url": "https://comedybar.ca/shows/studio-saturdays",
    "source": "https://comedybar.ca/shows/studio-saturdays",
    "checked": "2026-09-09",
    "description": "Buckle up for scenic and musical improv at its best as our CB PRO students hit the stage and bring the laughs!",
    "schedule": {
      "kind": "day",
      "date": "2026-09-19",
      "time": "06:00 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-studio-saturdays-2026-09-26",
    "title": "STUDIO SATURDAYS",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$13",
    "venue": "Comedy Bar Danforth - Studio Theatre",
    "address": "2800 Danforth Avenue, Toronto, ON, M4C 1M1",
    "url": "https://comedybar.ca/shows/studio-saturdays",
    "source": "https://comedybar.ca/shows/studio-saturdays",
    "checked": "2026-09-09",
    "description": "Buckle up for scenic and musical improv at its best as our CB PRO students hit the stage and bring the laughs!",
    "schedule": {
      "kind": "day",
      "date": "2026-09-26",
      "time": "06:00 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "evergreen-family-wander-2026-09-27",
    "title": "Family Wander",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "source": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "checked": "2026-09-09",
    "description": "Aug 16, Sept 27, Nov 15. Registration required.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-27"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-family-wander-2026-09-27",
    "title": "Family Wander",
    "category": "dropin",
    "art": "art-ravine",
    "entry": "Suggested $20 donation per family",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-work/activities/family-wanders/",
    "source": "https://www.evergreen.ca/evergreen-brick-work/activities/family-wanders/",
    "checked": "2026-09-09",
    "description": "Guided walk exploring the nature at Evergreen Brick Works; takes place rain or shine. Registration required.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-27",
      "time": "10:00 am – 11:00 am"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-intro-to-forest-bathing-walk-2026-09-20",
    "title": "Intro to Forest Bathing Walk",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "source": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "checked": "2026-09-09",
    "description": "Sep 20. Save your spot.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-20"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-little-discoveries-2026-09-27",
    "title": "Little Discoveries",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "source": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "checked": "2026-09-09",
    "description": "Aug 23 & Sept 27. Register your kid today.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-27"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-mighty-minis-child-portrait-photos-2026-09-13",
    "title": "Mighty Minis: Child Portrait Photos",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "source": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "checked": "2026-09-09",
    "description": "Sept 13 & 20. Book your session.",
    "schedule": {
      "kind": "range",
      "start": "2026-09-13",
      "end": "2026-09-20"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-monthly-roller-skating-night-2026-09-20",
    "title": "Monthly Roller Skating Night",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "source": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "checked": "2026-09-09",
    "description": "Aug 28, Sept 20. Rent skates or BYO.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-20"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-ontario-artisan-market-and-ontario-vintage-marke-2026-09-13",
    "title": "Ontario Artisan Market and Ontario Vintage Market",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "source": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "checked": "2026-09-09",
    "description": "Two great markets in one amazing place. Shop a wide range of vendors offering unique, handmade, locally made and sustainable products, plus carefully curated antiques and vintage.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-13",
      "time": "10am-3pm"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-ontario-artisan-market-and-ontario-vintage-marke-2026-09-20",
    "title": "Ontario Artisan Market and Ontario Vintage Market",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "source": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "checked": "2026-09-09",
    "description": "Two great markets in one amazing place. Connect with local artists and makers, and treat yourself to the beauty of craft.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-20",
      "time": "10am-3pm"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-ontario-artisan-market-and-ontario-vintage-marke-2026-09-27",
    "title": "Ontario Artisan Market and Ontario Vintage Market",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "source": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "checked": "2026-09-09",
    "description": "Two great markets in one amazing place. Support and shop from over 40 incredible local artists and makers.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-27",
      "time": "10am-3pm"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-ontario-artisan-market-and-ontario-vintage-marke-2026-10-04",
    "title": "Ontario Artisan Market and Ontario Vintage Market",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "source": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "checked": "2026-09-09",
    "description": "Two great markets in one amazing place. Your one-stop for local vintage and artisan wares.",
    "schedule": {
      "kind": "day",
      "date": "2026-10-04",
      "time": "10am-3pm"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "luma-a-new-creative-paradigm-consistent-cinematic-ai--2026-09-10",
    "title": "A New Creative Paradigm: Consistent, Cinematic AI Video Powered by Kling AI",
    "category": "social",
    "art": "art-mic",
    "entry": "Free",
    "venue": "Metro Toronto Convention Centre",
    "address": "Toronto, Ontario",
    "url": "https://luma.com/yww621x0",
    "source": "https://luma.com/yww621x0",
    "checked": "2026-09-09",
    "description": "Event Format: Panel Discussion Venue: Stage B, Metro Toronto Convention Centre Presented by Kling AI, this panel explores how AI video is redefining the way cinematic stories are imagined, developed, and produced…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-10"
    },
    "scrapedFrom": "luma",
    "via": "json-ld"
  },
  {
    "id": "luma-aaif-toronto-agentic-ai-night-2026-09-10",
    "title": "AAIF Toronto: Agentic AI Night",
    "category": "social",
    "art": "art-mic",
    "entry": "Free",
    "venue": "Arctiq",
    "address": "Toronto, Ontario",
    "url": "https://luma.com/p6vg7zag",
    "source": "https://luma.com/p6vg7zag",
    "checked": "2026-09-09",
    "description": "Everyone can build an agent that demos. Almost nobody can keep one running…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-10"
    },
    "scrapedFrom": "luma",
    "via": "json-ld"
  },
  {
    "id": "luma-chatbase-x-sentry-padel-tournament-2026-09-10",
    "title": "Chatbase x Sentry Padel Tournament",
    "category": "social",
    "art": "art-mic",
    "entry": "Free",
    "venue": "The Pad | Toronto Padel Club",
    "address": "Toronto, Ontario",
    "url": "https://luma.com/chatbase-3cch",
    "source": "https://luma.com/chatbase-3cch",
    "checked": "2026-09-09",
    "description": "Toronto tech is hitting the padel court. 🎾 Join us for the Chatbase x Sentry Padel Tournament at The Pad, Toronto's original padel club on Cherry Street…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-10"
    },
    "scrapedFrom": "luma",
    "via": "json-ld"
  },
  {
    "id": "luma-the-domino-club-tile-room-2026-09-10",
    "title": "The Domino Club: Tile Room",
    "category": "social",
    "art": "art-mic",
    "entry": "$10",
    "venue": "520 Cafe Bar",
    "address": "Toronto, Ontario",
    "url": "https://luma.com/gtliwka8",
    "source": "https://luma.com/gtliwka8",
    "checked": "2026-09-09",
    "description": "If you get lost on your way to the Tile Room, just follow the light. The tables are open once again, both inside and outside. If you’ve been with us since beginning, you’ll know what to expect…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-10"
    },
    "scrapedFrom": "luma",
    "via": "json-ld"
  },
  {
    "id": "luma-toronto-book-launch-for-the-campfire-method-2026-09-09",
    "title": "Toronto Book Launch for \"The Campfire Method\"",
    "category": "social",
    "art": "art-mic",
    "entry": "Free",
    "venue": "Mentimeter North America Inc",
    "address": "Toronto, Ontario",
    "url": "https://luma.com/do33l36g",
    "source": "https://luma.com/do33l36g",
    "checked": "2026-09-09",
    "description": "Join me in Toronto to launch “The Campfire Method” Come experience what warming up a room without awkward icebreakers actually feels like. ABOUT THE EVENT This is not a book reading…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-09"
    },
    "scrapedFrom": "luma",
    "via": "json-ld"
  },
  {
    "id": "tpl-laverne-cox-jason-stanley-identity-power-and-the-2026-09-09",
    "title": "Laverne Cox & Jason Stanley: Identity, Power and the Politics of Our Time",
    "category": "dropin",
    "art": "art-books",
    "venue": "Toronto Reference Library",
    "address": "789 Yonge Street, Toronto, ON, M4W 2G8",
    "url": "https://tpl.bibliocommons.com/v2/events/6a85b4814c610f0038954eb9",
    "source": "https://tpl.bibliocommons.com/v2/events/6a85b4814c610f0038954eb9",
    "checked": "2026-09-09",
    "description": "Join actor and activist Laverne Cox and philosopher Jason Stanley for a conversation about the political forces reshaping our world.As civil rights, historical truth and democratic norms come under pressure in the…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-09"
    },
    "scrapedFrom": "tpl",
    "via": "json-ld"
  }
];
