/* Generated by scrape/run.mjs — do not edit by hand.
   Hand-written listings live in data.js; these are polled from the sources
   in scrape/sources.mjs and merged at load. */

const SCRAPED = [
  {
    "id": "baddog-academy-showcase-narrative-process-sweet-sweet-f-2026-09-23",
    "title": "Academy Showcase: Narrative Process & Sweet Sweet Friends",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Sweet Action Theatre",
    "address": "180 Shaw Street, Toronto, ON, M6J 2W5, Canada",
    "url": "https://baddogtheatre.com/whats-on",
    "source": "https://baddogtheatre.com/whats-on",
    "checked": "2026-09-11",
    "description": "Listed by Bad Dog Theatre.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-23",
      "time": "7:00 PM – 8:00 PM"
    },
    "scrapedFrom": "baddog",
    "via": "model"
  },
  {
    "id": "baddog-sweet-sweet-friends-2026-09-16",
    "title": "Sweet Sweet Friends",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Sweet Sweet Friends",
    "address": "180 Shaw Street\nToronto, ON, M6J 2W5\nCanada",
    "url": "https://baddogtheatre.com/whats-on/2026/9/16/sweet-sweet-friends",
    "source": "https://baddogtheatre.com/whats-on/2026/9/16/sweet-sweet-friends",
    "checked": "2026-09-11",
    "description": "BAD DOG THEATRE PRESENTS SWEET SWEET FRIENDS Tonight, a delectable selection of RISING STARS take the Sweet Sweet Wednesday stage once more to bring you an extra helping of laughs!…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-16"
    },
    "scrapedFrom": "baddog",
    "via": "json-ld"
  },
  {
    "id": "baddog-the-audition-2026-09-11",
    "title": "The Audition",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Comedy Bar Bloor",
    "address": "945 Bloor Street West\nToronto, ON, M6H 1L5\nCanada",
    "url": "https://baddogtheatre.com/whats-on/2026/9/4/the-audition-rz4dm",
    "source": "https://baddogtheatre.com/whats-on/2026/9/4/the-audition-rz4dm",
    "checked": "2026-09-11",
    "description": "Performers work through cold reads, callbacks and strange direction as the audition process spirals in unpredictable ways — completely improvised and never the same twice.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11"
    },
    "scrapedFrom": "baddog",
    "via": "json-ld"
  },
  {
    "id": "baddog-the-audition-2026-09-18",
    "title": "The Audition",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Comedy Bar Bloor",
    "address": "945 Bloor Street West\nToronto, ON, M6H 1L5\nCanada",
    "url": "https://baddogtheatre.com/whats-on/2026/9/4/the-audition-rz4dm-977bl",
    "source": "https://baddogtheatre.com/whats-on/2026/9/4/the-audition-rz4dm-977bl",
    "checked": "2026-09-11",
    "description": "Performers move through cold reads, callbacks, strange direction and unexpected twists as the audition process spirals — completely improvised and never the same twice.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-18"
    },
    "scrapedFrom": "baddog",
    "via": "json-ld"
  },
  {
    "id": "baddog-the-bucket-show-2026-09-16",
    "title": "The Bucket Show",
    "category": "comedy",
    "art": "art-neon",
    "venue": "Sweet Action",
    "address": "180 Shaw Street, Unit #106, Toronto, ON, M6J 2W5, Canada",
    "url": "https://baddogtheatre.com/whats-on",
    "source": "https://baddogtheatre.com/whats-on",
    "checked": "2026-09-11",
    "description": "Listed by Bad Dog Theatre.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-16",
      "time": "8:30 PM – 9:30 PM"
    },
    "scrapedFrom": "baddog",
    "via": "model"
  },
  {
    "id": "bentway-a-persistent-crossing-2026-09-11",
    "title": "A Persistent Crossing",
    "category": "architecture",
    "art": "art-skates",
    "venue": "Bentway Staging Grounds",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-11",
    "description": "An immersive installation of human silhouettes, native vegetation and Ontario pollinators, on view through spring 2027.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-artist-talk-with-paul-ram-rez-jonas-2026-09-15",
    "title": "Artist Talk with Paul Ramírez Jonas",
    "category": "architecture",
    "art": "art-skates",
    "venue": "The Bentway",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-11",
    "description": "A conversation with the artist about his work and his long-time engagement with democracy, participation and the public realm, marking the Canadian premiere of Public Trust.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-15"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-make-the-world-go-round-2026-09-11",
    "title": "Make the World Go Round",
    "category": "architecture",
    "art": "art-skates",
    "venue": "Bentway Skate Trail",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-11",
    "description": "A signature mural wraps the columns of the skate trail with illustrated sights and scenes of Toronto.",
    "schedule": {
      "kind": "range",
      "start": "2026-09-11",
      "end": "2026-10-04"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-petal-and-stone-2026-09-11",
    "title": "Petal and Stone",
    "category": "architecture",
    "art": "art-skates",
    "venue": "The Bentway",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-11",
    "description": "A 10,000 square-foot mural across a concrete expanse between The Bentway and Exhibition Place, depicting site memory, native flora and symbolic passage. On view through 2027.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-public-trust-2026-09-15",
    "title": "Public Trust",
    "category": "architecture",
    "art": "art-skates",
    "venue": "The Bentway",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-11",
    "description": "Visitors make written promises to themselves and their community in a non-partisan installation that turns civic engagement into something personal and playful.",
    "schedule": {
      "kind": "range",
      "start": "2026-09-15",
      "end": "2026-10-04"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-roller-skate-lessons-2026-09-11",
    "title": "Roller Skate Lessons",
    "category": "architecture",
    "art": "art-skates",
    "venue": "The Bentway",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-11",
    "description": "Weekly lessons for beginners to build basic skills and confidence on wheels around the figure-eight trail.",
    "schedule": {
      "kind": "range",
      "start": "2026-09-11",
      "end": "2026-09-25"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-roller-skate-lessons-2026-09-11",
    "title": "Roller Skate Lessons",
    "category": "architecture",
    "art": "art-skates",
    "entry": "$15 (equipment rentals not included)",
    "venue": "The Bentway Skate Trail",
    "address": "250 Fort York Boulevard, Toronto, ON, Canada",
    "url": "https://thebentway.ca/event/roller-skate-lessons-2026/",
    "source": "https://thebentway.ca/event/roller-skate-lessons-2026/",
    "checked": "2026-09-11",
    "description": "A 45-minute beginner lesson on the figure-eight skate trail under the Gardiner, covering balance and striding, turning and stopping, safe falling and basic edge work…",
    "schedule": {
      "kind": "range",
      "start": "2026-09-11",
      "end": "2026-09-25"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-roller-skate-lessons-september-11-2026-09-11",
    "title": "Roller Skate Lessons: September 11",
    "category": "architecture",
    "art": "art-skates",
    "venue": "The Bentway",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-11",
    "description": "Instructors teach novice skaters basic roller skating skills and how to handle the figure-eight trail.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11",
      "time": "6:30pm-7:30pm and 7:30pm-8:30pm"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-roller-skate-rentals-2026-09-11",
    "title": "Roller Skate Rentals",
    "category": "architecture",
    "art": "art-skates",
    "venue": "The Bentway Skate Trail",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-11",
    "description": "Rent roller skates and protective gear from the Skate Rental Container on site and use the skate trail.",
    "schedule": {
      "kind": "range",
      "start": "2026-09-11",
      "end": "2026-09-27"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "bentway-skate-trail-closed-2026-09-12",
    "title": "Skate Trail Closed",
    "category": "architecture",
    "art": "art-skates",
    "venue": "The Bentway",
    "address": "250 Fort York Blvd, Toronto, ON M5V 3K9",
    "url": "https://thebentway.ca/whats-on/",
    "source": "https://thebentway.ca/whats-on/",
    "checked": "2026-09-11",
    "description": "Listed by The Bentway.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-12"
    },
    "scrapedFrom": "bentway",
    "via": "model"
  },
  {
    "id": "comedybar-clash-talk-a-competitive-talk-show-with-good-not-2026-09-25",
    "title": "Clash Talk: A Competitive Talk Show with Good Noticings",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$41.94",
    "venue": "The Randolph Theatre",
    "address": "736 Bathurst St, Toronto, ON M5S 2R4",
    "url": "https://comedybar.ca/shows/clash-talk-a-competitive-talk-show-with-good-noticings",
    "source": "https://comedybar.ca/shows/clash-talk-a-competitive-talk-show-with-good-noticings",
    "checked": "2026-09-11",
    "description": "A live panel show in which two hosts interview, bond and clash with special guests, and the audience votes on who wins.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-25",
      "time": "7:00 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-nice-time-2026-09-16",
    "title": "Nice Time",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$10",
    "venue": "Comedy Bar Bloor (Cabaret)",
    "address": "945 Bloor Street W, Toronto, ON, M6H 1L5",
    "url": "https://comedybar.ca/shows/nice-time",
    "source": "https://comedybar.ca/shows/nice-time",
    "checked": "2026-09-11",
    "description": "Toronto comedians improvise a brand new hour-long show, with a rotating cast of guest improvisers and live music.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-16",
      "time": "8:00 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-nice-time-2026-09-23",
    "title": "Nice Time",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$10",
    "venue": "Comedy Bar Bloor (Cabaret)",
    "address": "945 Bloor Street W, Toronto, ON, M6H 1L5",
    "url": "https://comedybar.ca/shows/nice-time",
    "source": "https://comedybar.ca/shows/nice-time",
    "checked": "2026-09-11",
    "description": "Toronto comedians improvise a brand new hour-long show, with a rotating cast of guest improvisers and live music.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-23",
      "time": "8:00 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-roast-battle-toronto-2026-09-11",
    "title": "Roast Battle Toronto",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$23 online, $25 at the door",
    "venue": "Comedy Bar Bloor (Cabaret)",
    "address": "945 Bloor Street W, Toronto, ON, M6H 1L5",
    "url": "https://comedybar.ca/shows/roast-battle-toronto",
    "source": "https://comedybar.ca/shows/roast-battle-toronto",
    "checked": "2026-09-11",
    "description": "Toronto comedians face each other in head-to-head insult battles, trading written punchlines to climb the local Roast rankings toward a city championship. Content warning in effect; viewer discretion strongly advised.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11",
      "time": "10:00 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-studio-mondays-2026-09-14",
    "title": "STUDIO MONDAYS",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$13",
    "venue": "Comedy Bar Danforth - Studio Theatre",
    "address": "2800 Danforth Avenue, Toronto, ON, M4C 1M1",
    "url": "https://comedybar.ca/shows/studio-mondays",
    "source": "https://comedybar.ca/shows/studio-mondays",
    "checked": "2026-09-11",
    "description": "Three sets in one night: a fully improvised narrative built from an audience suggestion, a set from a CB PRO troupe (longform, sketch or improvised musical), and The Jim-Jam, a bucket-style improv jam anyone can join…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-14",
      "time": "8:30 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-studio-mondays-2026-09-21",
    "title": "STUDIO MONDAYS",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$13",
    "venue": "Comedy Bar Danforth - Studio Theatre",
    "address": "2800 Danforth Avenue, Toronto, ON, M4C 1M1",
    "url": "https://comedybar.ca/shows/studio-mondays",
    "source": "https://comedybar.ca/shows/studio-mondays",
    "checked": "2026-09-11",
    "description": "Three sets in one night: a fully improvised narrative built from an audience suggestion, a set from a CB PRO troupe (longform, sketch or improvised musical), and The Jim-Jam, a bucket-style improv jam anyone can join…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-21",
      "time": "8:30 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-studio-mondays-2026-09-28",
    "title": "STUDIO MONDAYS",
    "category": "comedy",
    "art": "art-neon",
    "entry": "$13",
    "venue": "Comedy Bar Danforth - Studio Theatre",
    "address": "2800 Danforth Avenue, Toronto, ON, M4C 1M1",
    "url": "https://comedybar.ca/shows/studio-mondays",
    "source": "https://comedybar.ca/shows/studio-mondays",
    "checked": "2026-09-11",
    "description": "Three sets in one night: a fully improvised narrative built from an audience suggestion, a set from a CB PRO troupe (longform, sketch or improvised musical), and The Jim-Jam, a bucket-style improv jam anyone can join…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-28",
      "time": "8:30 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "comedybar-wheel-of-comedy-2026-09-14",
    "title": "Wheel Of Comedy",
    "category": "comedy",
    "art": "art-neon",
    "entry": "Online $15 / Door $20",
    "venue": "Comedy Bar Bloor (Cabaret)",
    "address": "945 Bloor Street W, Toronto, ON, M6H 1L5",
    "url": "https://comedybar.ca/shows/wheel-of-comedy",
    "source": "https://comedybar.ca/shows/wheel-of-comedy",
    "checked": "2026-09-11",
    "description": "Comedians drop their prepared material and spin a wheel that decides their set: crowd work, Q&A, audience suggestions, freestyle rap, roasting the hosts, impressions, slideshows and other challenges that change each…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-14",
      "time": "9:30 PM"
    },
    "scrapedFrom": "comedybar",
    "via": "model"
  },
  {
    "id": "evergreen-family-wander-2026-09-27",
    "title": "Family Wander",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "source": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "checked": "2026-09-11",
    "description": "A guided family outing on the site; registration required.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-27"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-free-public-site-tours-of-evergreen-brick-works-2026-09-12",
    "title": "Free Public Site Tours of Evergreen Brick Works",
    "category": "dropin",
    "art": "art-ravine",
    "entry": "Free",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-work/activities/site-tours/",
    "source": "https://www.evergreen.ca/evergreen-brick-work/activities/site-tours/",
    "checked": "2026-09-11",
    "description": "An hour-long guided walk, meeting at the Welcome Desk in Building 14 and running rain or shine…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-12"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-intro-to-forest-bathing-walk-2026-09-20",
    "title": "Intro to Forest Bathing Walk",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "source": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "checked": "2026-09-11",
    "description": "An introductory slow walk in nature; spots must be reserved.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-20"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-little-discoveries-2026-09-27",
    "title": "Little Discoveries",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "source": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "checked": "2026-09-11",
    "description": "A program for young kids; registration required.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-27"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-mighty-minis-child-portrait-photos-2026-09-13",
    "title": "Mighty Minis: Child Portrait Photos",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "source": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "checked": "2026-09-11",
    "description": "Bookable portrait photo sessions for children.",
    "schedule": {
      "kind": "range",
      "start": "2026-09-13",
      "end": "2026-09-20"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-monthly-roller-skating-night-2026-09-20",
    "title": "Monthly Roller Skating Night",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "source": "https://www.evergreen.ca/evergreen-brick-works/whats-on/",
    "checked": "2026-09-11",
    "description": "An evening of roller skating; rent skates on site or bring your own.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-20"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-ontario-artisan-market-and-ontario-vintage-marke-2026-09-13",
    "title": "Ontario Artisan Market and Ontario Vintage Market",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "source": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "checked": "2026-09-11",
    "description": "Over 40 local artists and makers sell handmade goods like jewellery, skin care, art and candles alongside vintage vendors with curated antiques…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-13",
      "time": "10am-3pm"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-ontario-artisan-market-and-ontario-vintage-marke-2026-09-20",
    "title": "Ontario Artisan Market and Ontario Vintage Market",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "source": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "checked": "2026-09-11",
    "description": "Shop handmade, locally made and sustainable products from local makers plus fresh curated vintage and antiques, with food vendors and drinks available on site.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-20",
      "time": "10am-3pm"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-ontario-artisan-market-and-ontario-vintage-marke-2026-09-27",
    "title": "Ontario Artisan Market and Ontario Vintage Market",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "source": "https://www.evergreen.ca/evergreen-brick-work/activities/ontario-artisan-market-ontario-vintage-market/",
    "checked": "2026-09-11",
    "description": "Shop handmade, locally made and sustainable products from local makers plus fresh curated vintage and antiques, with food vendors and drinks available on site.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-27",
      "time": "10am-3pm"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "evergreen-saturday-farmers-market-2026-09-12",
    "title": "Saturday Farmers Market",
    "category": "dropin",
    "art": "art-ravine",
    "venue": "Evergreen Brick Works",
    "address": "550 Bayview Ave, Toronto",
    "url": "https://www.evergreen.ca/evergreen-brick-work/activities/saturday-farmers-market/",
    "source": "https://www.evergreen.ca/evergreen-brick-work/activities/saturday-farmers-market/",
    "checked": "2026-09-11",
    "description": "A year-round farmers market where you can shop from Ontario farmers and producers based within 205 km of the site, plus a local food court. From May to October the market sets up outdoors under the pavilions.",
    "schedule": {
      "kind": "day",
      "date": "2026-09-12",
      "time": "8am – 1pm (Local Food Court open until 2pm)"
    },
    "scrapedFrom": "evergreen",
    "via": "model"
  },
  {
    "id": "luma-currently-reading-a-sunday-morning-mid-book-club-2026-09-13",
    "title": "Currently Reading - a Sunday morning mid-book club at Book People",
    "category": "social",
    "art": "art-mic",
    "entry": "Free",
    "venue": "Book People on Queen",
    "address": "Toronto, Ontario",
    "url": "https://luma.com/gp4fjufz",
    "source": "https://luma.com/gp4fjufz",
    "checked": "2026-09-11",
    "description": "Bring the book you're currently reading. That's it - that's the whole assignment. No assigned reading, no discussion questions, no pressure to have finished anything…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-13"
    },
    "scrapedFrom": "luma",
    "via": "json-ld"
  },
  {
    "id": "luma-designwalks-toronto-walk-11-2026-09-12",
    "title": "designwalks™ - Toronto - Walk 11",
    "category": "social",
    "art": "art-mic",
    "entry": "Free",
    "venue": "Trinity Bellwoods Park",
    "address": "Toronto, Ontario",
    "url": "https://luma.com/qmvmmfvk",
    "source": "https://luma.com/qmvmmfvk",
    "checked": "2026-09-11",
    "description": "designwalks™ - Toronto About Walk 11: 📍 Trinity Bellwoods Park (We’ll be meeting at the intersection of Strachan Ave & Queen St W.) 🕒 3:00-5:00p.m., Saturday, September 12…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-12"
    },
    "scrapedFrom": "luma",
    "via": "json-ld"
  },
  {
    "id": "luma-pokemon-diorama-workshop-hosted-by-sticktors-ft--2026-09-11",
    "title": "Pokemon Diorama Workshop hosted by Sticktors ft. Menu by Loaf of a Dough Girl",
    "category": "social",
    "art": "art-mic",
    "entry": "$50",
    "venue": "Again Again",
    "address": "Toronto, Ontario",
    "url": "https://luma.com/xn7h0mxf",
    "source": "https://luma.com/xn7h0mxf",
    "checked": "2026-09-11",
    "description": "Come build the perfect little diorama for your favourite Pokémon! Using Poké Ball tins, we’ll create miniature scenes inspired by your favourite Pokémon…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11"
    },
    "scrapedFrom": "luma",
    "via": "json-ld"
  },
  {
    "id": "luma-step6ix-sunday-social-run-2026-09-13",
    "title": "Step6ix Sunday Social Run",
    "category": "social",
    "art": "art-mic",
    "entry": "Free",
    "venue": "Heval cafe",
    "address": "Toronto, Ontario",
    "url": "https://luma.com/b1q8dpsr",
    "source": "https://luma.com/b1q8dpsr",
    "checked": "2026-09-11",
    "description": "THIS SUNDAY٫ we’re taking the finish line to HEVAL!…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-13"
    },
    "scrapedFrom": "luma",
    "via": "json-ld"
  },
  {
    "id": "tpl-microsoft-application-series-2026-09-11",
    "title": "Microsoft Application Series",
    "category": "dropin",
    "art": "art-books",
    "venue": "Humberwood",
    "address": "850 Humberwood Boulevard, Toronto, ON, M9W 7A6",
    "url": "https://tpl.bibliocommons.com/v2/events/6a88a5fa3b6c71003e5a6edb",
    "source": "https://tpl.bibliocommons.com/v2/events/6a88a5fa3b6c71003e5a6edb",
    "checked": "2026-09-11",
    "description": "Are you interested in improving your computer skills?…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11"
    },
    "scrapedFrom": "tpl",
    "via": "json-ld"
  },
  {
    "id": "tpl-randy-boyagoda-lords-of-serendipity-2026-09-11",
    "title": "Randy Boyagoda: Lords of Serendipity",
    "category": "dropin",
    "art": "art-books",
    "venue": "Toronto Reference Library",
    "address": "789 Yonge Street, Toronto, ON, M4W 2G8",
    "url": "https://tpl.bibliocommons.com/v2/events/6a85b730fa71a30d92946b60",
    "source": "https://tpl.bibliocommons.com/v2/events/6a85b730fa71a30d92946b60",
    "checked": "2026-09-11",
    "description": "TPL presents novelist Randy Boyagoda in conversation with Parul Sehgal at the Toronto Reference Library's Appel Salon.In his wildly funny and richly observed new novel Lords of Serendipity, acclaimed author Randy…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11"
    },
    "scrapedFrom": "tpl",
    "via": "json-ld"
  },
  {
    "id": "tpl-wellness-recovery-action-plan-wrap-2026-09-11",
    "title": "Wellness Recovery Action Plan (WRAP)",
    "category": "dropin",
    "art": "art-books",
    "venue": "Toronto Reference Library",
    "address": "789 Yonge Street, Toronto, ON, M4W 2G8",
    "url": "https://tpl.bibliocommons.com/v2/events/6a061f5ac6a1dc3d00d3c004",
    "source": "https://tpl.bibliocommons.com/v2/events/6a061f5ac6a1dc3d00d3c004",
    "checked": "2026-09-11",
    "description": "WRAP is for anyone looking to strengthen their well-being—whether you’re supporting your mental health, managing stress, or simply wanting to feel more balanced and resilient in daily life.nbsp;Participants will receive…",
    "schedule": {
      "kind": "day",
      "date": "2026-09-11"
    },
    "scrapedFrom": "tpl",
    "via": "json-ld"
  }
];
